<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="diiwa_base_scene" >

  <xacro:arg name="scene"		default=""/>
  <xacro:arg name="hardware_interface"	default="PositionJointInterface"/>

  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="a_iiwa_x" value="0"/>
  <xacro:property name="a_iiwa_y" value="-0.4875"/>
  <xacro:property name="b_iiwa_x" value="0"/>
  <xacro:property name="b_iiwa_y" value="0.4875"/>
  <xacro:property name="bots_z"	  value="0.785"/>

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <link name="ground"/>

  <xacro:include filename="$(find aist_description
			   )/objects/urdf/aist_box.urdf.xacro"/>
  <xacro:property name="table_w" value="0.9"/>
  <xacro:property name="table_l" value="0.75"/>
  <xacro:property name="table_h" value="0.01"/>
  <xacro:aist_box name="workbox"
		  width="${table_w}" length="${table_l}" height="${table_h}"
		  parent="ground">
    <origin xyz="${-table_w/2} ${-table_l/2} ${bots_z - table_h}" rpy="0 0 0"/>
  </xacro:aist_box>
  <link name="workspace_center"/>
  <joint name="ground_to_workspace" type="fixed">
    <parent link="ground"/>
    <child  link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- robot arms -->
  <xacro:include filename="$(find aist_description
			   )/devices/urdf/iiwa14.urdf.xacro"/>
  <xacro:iiwa14 robot_name="a_iiwa" parent="ground"
		hardware_interface="$(arg hardware_interface)">
    <origin xyz="${a_iiwa_x} ${a_iiwa_y} ${bots_z}" rpy="0 0 ${pi/2}"/>
  </xacro:iiwa14>
  <xacro:iiwa14 robot_name="b_iiwa" parent="ground"
		hardware_interface="$(arg hardware_interface)">
    <origin xyz="${b_iiwa_x} ${b_iiwa_y} ${bots_z}" rpy="0 0 ${-pi/2}"/>
  </xacro:iiwa14>

  <!-- Attach grippers -->
  <xacro:include filename="$(find aist_description
  			   )/devices/urdf/robotiq_85_gripper_with_tip_link.urdf.xacro"/>
  <xacro:robotiq_85_gripper_with_tip_link prefix="a_iiwa_"
  					  parent="a_iiwa_ee_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_85_gripper_with_tip_link>

  <xacro:include filename="$(find aist_description
			   )/devices/urdf/single_suction_gripper.urdf.xacro"/>
  <xacro:single_suction_gripper prefix="b_iiwa_" parent="b_iiwa_ee_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:single_suction_gripper>

  <!-- Gazebo plugins for IIWA arms -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
    <plugin name="a_bot_ft_sensor" filename="libgazebo_ros_ft_sensor.so">
      <topicName>/state/CartesianWrench</topicName>
      <jointName>a_iiwa_joint_7</jointName>
    </plugin>
  </gazebo>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world"/>
  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Include indivisual scene file -->
  <xacro:if value="${'$(arg scene)' != ''}">
    <xacro:include filename="$(find aist_description)/scenes/urdf/$(arg
			     scene).urdf.xacro"/>
  </xacro:if>

</robot>
