<?xml version="1.0"?>
<robot name="iiwa14" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="hardware_interface" default="PositionJointInterface"/>
  <xacro:arg name="end_effector" default=""/>

  <xacro:arg name="robot_name_1" default="a_iiwa"/>
  <xacro:arg name="origin_x_1" default="0"/>
  <xacro:arg name="origin_y_1" default="0"/>
  <xacro:arg name="origin_z_1" default="0"/>
  <xacro:arg name="origin_roll_1"  default="0"/>
  <xacro:arg name="origin_pitch_1" default="0"/>
  <xacro:arg name="origin_yaw_1"   default="0"/>

  <xacro:arg name="robot_name_2" default="b_iiwa"/>
  <xacro:arg name="origin_x_2" default="0"/>
  <xacro:arg name="origin_y_2" default="1.2"/>
  <xacro:arg name="origin_z_2" default="0"/>
  <xacro:arg name="origin_roll_2"  default="0"/>
  <xacro:arg name="origin_pitch_2" default="0"/>
  <xacro:arg name="origin_yaw_2"   default="0"/>

  <xacro:arg name="exist_objs" default="true"/>

  <!-- Import Rviz colors -->
  <xacro:include filename="$(find iiwa_description)/urdf/materials.xacro" />
  <!--Import the lbr iiwa macro -->
  <xacro:include filename="$(find iiwa_description)/urdf/iiwa14.xacro"/>

  <xacro:include filename="$(find aist_description)/objects/urdf/aist_box.urdf.xacro"/>

  <xacro:property name="bots_z"  value="0.80" />

  <xacro:property name="table_w" value="0.80" />
  <xacro:property name="table_l" value="0.90" />
  <xacro:property name="table_h" value="0.01" />

  <xacro:property name="table2_w" value="0.40" />
  <xacro:property name="table2_l" value="0.60" />
  <xacro:property name="table2_h" value="0.01" />

  <xacro:property name="origin_x_1" value="$(arg origin_x_1)" />
  <xacro:property name="origin_y_1" value="$(arg origin_y_1)" />
  <xacro:property name="origin_z_1" value="$(arg origin_z_1)" />
  <xacro:property name="origin_roll_1"  value="$(arg origin_roll_1)" />
  <xacro:property name="origin_pitch_1" value="$(arg origin_pitch_1)" />
  <xacro:property name="origin_yaw_1"   value="$(arg origin_yaw_1)" />
  <xacro:property name="origin_x_2" value="$(arg origin_x_2)" />
  <xacro:property name="origin_y_2" value="$(arg origin_y_2)" />
  <xacro:property name="origin_z_2" value="$(arg origin_z_2)" />
  <xacro:property name="origin_roll_2"  value="$(arg origin_roll_2)" />
  <xacro:property name="origin_pitch_2" value="$(arg origin_pitch_2)" />
  <xacro:property name="origin_yaw_2"   value="$(arg origin_yaw_2)" />

  <xacro:property name="end_effector" value="$(arg end_effector)" />

  <xacro:property name="exist_objs" value="$(arg exist_objs)" />

  <link name="world"/>

  <link name="ground"/>

  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="workspace_center"/>
  <joint name="ground_to_workspace" type="fixed">
    <parent link="ground"/>
    <child link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <xacro:if value="${exist_objs == 'true'}">
    <xacro:aist_box name="$(arg robot_name_1)_workbox"
            width="${table_w}" length="${table_l}" height="${table_h}"
            parent="ground">
      <origin xyz="${-table_w/2 + origin_x_1} ${-table_l/2 + origin_y_1} ${bots_z - table_h}" rpy="0 0 0"/>
    </xacro:aist_box>
    <xacro:aist_box name="$(arg robot_name_2)_workbox"
            width="${table_w}" length="${table_l}" height="${table_h}"
            parent="ground">
      <origin xyz="${-table_w/2 + origin_x_2} ${-table_l/2 + origin_y_2} ${bots_z - table_h}" rpy="0 0 0"/>
    </xacro:aist_box>
    <xacro:aist_box name="$(arg robot_name_1)_table1"
            width="${table2_w}" length="${table2_l}" height="${table2_h}"
            parent="ground">
      <origin xyz="${origin_x_1 + 0.6} ${origin_y_1 - 0.3} ${bots_z + 0.35 - table2_h}" rpy="0 0 0"/>
    </xacro:aist_box>
    <xacro:aist_box name="$(arg robot_name_1)_table2"
            width="${table2_l}" length="${table2_w}" height="${table2_h}"
            parent="ground">
      <origin xyz="${origin_x_1 + 0.2} ${origin_y_1 + 0.4} ${bots_z + 0.35 - table2_h}" rpy="0 0 0"/>
    </xacro:aist_box>
    <xacro:aist_box name="$(arg robot_name_2)_table1"
            width="${table2_w}" length="${table2_l}" height="${table2_h}"
            parent="ground">
      <origin xyz="${origin_x_2 + 0.6} ${origin_y_2 - 0.3} ${bots_z + 0.35 - table2_h}" rpy="0 0 0"/>
    </xacro:aist_box>
    <xacro:aist_box name="$(arg robot_name_2)_table2"
            width="${table2_l}" length="${table2_w}" height="${table2_h}"
            parent="ground">
      <origin xyz="${origin_x_2 + 0.2} ${origin_y_2 + 0.4} ${bots_z + 0.35 - table2_h}" rpy="0 0 0"/>
    </xacro:aist_box>
  </xacro:if>

  <!-- a_iiwa : iiwa -->
  <xacro:iiwa14 hardware_interface="$(arg hardware_interface)" robot_name="$(arg robot_name_1)" parent="ground">
    <origin xyz="${origin_x_1} ${origin_y_1} ${origin_z_1 + bots_z}" rpy="${origin_roll_1} ${origin_pitch_1} ${origin_yaw_1}" />
  </xacro:iiwa14>

  <!-- b_iiwa : iiwa -->
  <xacro:iiwa14 hardware_interface="$(arg hardware_interface)" robot_name="$(arg robot_name_2)" parent="ground">
    <origin xyz="${origin_x_2} ${origin_y_2} ${origin_z_2 + bots_z}" rpy="${origin_roll_2} ${origin_pitch_2} ${origin_yaw_2}" />
  </xacro:iiwa14>

  <!-- bh282 -->
  <xacro:if value="${end_effector == 'bh282'}">
    <xacro:include filename="$(find barrett_hand_description)/urdf/bh282.urdf.xacro"/>
    <xacro:bhand_macro name="$(arg robot_name_1)_bh" parent="$(arg robot_name_1)_link_ee">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:bhand_macro>
    <xacro:include filename="$(find barrett_hand_description)/urdf/bh282.urdf.xacro"/>
    <xacro:bhand_macro name="$(arg robot_name_2)_bh" parent="$(arg robot_name_2)_link_ee">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:bhand_macro>
  </xacro:if>

  <!-- robotiq85gripper -->
  <xacro:if value="${end_effector == 'robotiq85gripper'}">
    <xacro:include filename="$(find robotiq_description)/urdf/robotiq_85_gripper.urdf.xacro"/>
    <xacro:robotiq_85_gripper prefix="$(arg robot_name_1)_r85g" parent="$(arg robot_name_1)_link_ee">
      <origin xyz="0 0 0" rpy="0 ${-pi/2} 0" />
    </xacro:robotiq_85_gripper>
    <xacro:include filename="$(find robotiq_description)/urdf/robotiq_85_gripper.urdf.xacro"/>
    <xacro:robotiq_85_gripper prefix="$(arg robot_name_2)_r85g" parent="$(arg robot_name_2)_link_ee">
      <origin xyz="0 0 0" rpy="0 ${-pi/2} 0" />
    </xacro:robotiq_85_gripper>
  </xacro:if>

</robot>
