<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="pgrp_base_scene" >

  <xacro:arg name="scene" default=""/>

  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="a_bot_x" value="0"/>
  <xacro:property name="a_bot_y" value="-0.4875"/>
  <!-- <xacro:property name="a_bot_theta" value="${pi}"/> -->
  <xacro:property name="b_bot_x" value="0"/>
  <xacro:property name="b_bot_y" value="0.4875"/>
  <xacro:property name="b_bot_theta" value="${pi}"/>

  <xacro:property name="bots_z" value="0.77"/>

  <!-- This is the main file defining our robot arrangement and physical environment. -->

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <link name="ground"/>

  <xacro:include filename="$(find aist_description)/objects/urdf/aist_box.urdf.xacro"/>
  <xacro:property name="table_w" value="0.9"/>
  <xacro:property name="table_l" value="1.8"/>
  <xacro:property name="table_h" value="0.01"/>
  <xacro:aist_box name="workbox"
		  width="${table_w}" length="${table_l}" height="${table_h}"
		  parent="ground">
    <origin xyz="${-table_w/2} ${-table_l/2} ${bots_z - table_h}" rpy="0 0 0"/>
  </xacro:aist_box>
  <link name="workspace_center"/>
  <joint name="ground_to_workspace" type="fixed">
    <parent link="ground"/>
    <child  link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- robot arms -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro"/>
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro"/>
  <xacro:ur5_robot prefix="a_bot_" joint_limited="false"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"
    kinematics_file="${load_yaml(
		     '$(find ur_description)/config/ur5_default.yaml')}"/>

  <xacro:ur5_robot prefix="b_bot_" joint_limited="false"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"
    kinematics_file="${load_yaml(
		     '$(find ur_description)/config/ur5_default.yaml')}"/>

  <joint name="ground_a_bot_joint" type="fixed">
    <parent link="ground"/>
    <child  link="a_bot_base_link"/>
    <origin xyz="${a_bot_x} ${a_bot_y} ${bots_z}" rpy="0 0 0"/>
  </joint>

  <joint name="ground_b_bot_joint" type="fixed">
    <parent link="ground"/>
    <child  link="b_bot_base_link"/>
    <origin xyz="${b_bot_x} ${b_bot_y} ${bots_z}" rpy="0 0 ${b_bot_theta}"/>
  </joint>

  <!-- Spawn and attach force sensor -->
  <xacro:include filename="$(find aist_ftsensor)/urdf/ft300.urdf.xacro"/>
  <xacro:ft300 prefix="a_bot_" parent="a_bot_ee_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:ft300>
  <xacro:ft300 prefix="b_bot_" parent="b_bot_ee_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:ft300>

  <!-- Spawn and attach gripper -->
  <xacro:include filename="$(find o2as_precision_gripper)/urdf/precision_gripper.urdf.xacro" />
  <xacro:precision_gripper prefix="a_bot_"
			   grippername="gripper"
			   parent="a_bot_ft300_flange_link">
    <origin xyz="-0.005 0 0" rpy="0 ${0.4*pi/180} ${0.5*pi/180}"/>
    <!-- <origin xyz="-0.004 0 0" rpy="${-pi/2} 0 0"/> -->
  </xacro:precision_gripper>

  <xacro:include filename="$(find aist_description)/devices/urdf/single_suction_gripper.urdf.xacro"/>
  <xacro:single_suction_gripper prefix="b_bot_"
  				parent="b_bot_ft300_flange_link">
    <origin xyz="0 0 0" rpy="0 ${0.3*pi/180} ${-0.6*pi/180}"/>
  </xacro:single_suction_gripper>

  <!-- Add virtual wall to avoid collisions-->
  <xacro:aist_box name="vwall1" width="0.01" length="0.3" height="0.5"
		  parent="ground" transparent="true">
    <origin xyz="0.45 -0.15 ${bots_z}" rpy="0 0 0"/>
  </xacro:aist_box>

  <!-- Add PhoXi 3D scanner -->
  <xacro:include filename="$(find aist_phoxi_camera)/urdf/phoxi_m_camera.urdf.xacro"/>
  <xacro:phoxi_m_camera prefix="a_" parent="ground">
    <origin xyz="0.481198965059
		 -0.0135554880428
		 1.40325326014"
	    rpy="${-152.362593503*pi/180}
		 ${-1.91385632258*pi/180}
		 ${86.7760807485*pi/180}"/>
  </xacro:phoxi_m_camera>

  <!-- Add RealSense camera -->
  <xacro:include filename="$(find aist_description)/devices/urdf/_sr305.urdf.xacro" />
  <xacro:sensor_sr305 prefix="a_bot_" parent="a_bot_wrist_2_link">
    <origin xyz="0.0326671856774
		 -0.063887034743
		 0.194855923541"
	    rpy="${-1.9802935144*pi/180}
		 ${10.1226491078*pi/180}
		 ${94.4366841644*pi/180}"/>
  </xacro:sensor_sr305>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world"/>
  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Include indivisual scene file -->
  <xacro:if value="${'$(arg scene)' != ''}">
    <xacro:include filename="$(find aist_description)/scenes/urdf/$(arg
			     scene).urdf.xacro"/>
  </xacro:if>

</robot>
