# This is just a wrapper around the move_group functionality

# Request
string			  planning_group   # "a_bot", "b_bot", "front_bots", "all_bots"
geometry_msgs/PoseStamped pose
float32                   speed
bool                      high_precision
string			  end_effector_link
bool			  move_lin
---
# Response
bool			  success
geometry_msgs/PoseStamped current_pose
