<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="aist_kitting_scene">
  <xacro:include filename="$(find aist_scene_description)/urdf/kitting_tray_with_partitions.xacro" />
  <xacro:include filename="$(find o2as_scene_description)/urdf/o2as_box.xacro" />

  <xacro:include filename="$(find aist_scene_description)/urdf/kitting_bins.xacro" />
  <xacro:include filename="$(find o2as_scene_description)/urdf/kitting_bin_macros.xacro" />

  <xacro:property name="tray_width" value=".210" />
  <xacro:property name="tray_length" value=".300" />
  <xacro:property name="tray_rack_width" value=".210" />
  <xacro:property name="tray_rack_length" value=".600" />
  <xacro:property name="tray_rack_height" value=".015" />
  <xacro:property name="bin_rack_width" value=".420" />
  <xacro:property name="bin_rack_length" value=".680" />
  <xacro:property name="bin_rack_height" value=".015" />


  <!-- add bin rack -->
  <xacro:o2as_box boxname="bin_rack" box_w="${bin_rack_width}" box_l="${bin_rack_length}" box_h="${bin_rack_height}" parent="workspace_center">
    <origin xyz="0 ${-bin_rack_length/2}  0" rpy="0 0 0" />
  </xacro:o2as_box>
  <link name="bin_rack_center" />
  <joint name="bin_rack_joint" type="fixed">
    <parent link="workspace_center" />
    <child link="bin_rack_center"/>
    <origin xyz="${bin_rack_width/2} 0 ${bin_rack_height}" rpy="0 0 0"/>
  </joint>

  <joint name="bin_rack_top_front_right_corner_joint" type="fixed">
    <parent link="bin_rack_center"/>
    <child link="bin_rack_top_front_right_corner"/>
    <origin rpy="0.0 0.0 0.0" xyz="${bin_rack_width/2} ${bin_rack_length/2} 0 "/>
  </joint>
  <link name="bin_rack_top_front_right_corner"/>

  <joint name="bin_rack_top_back_right_corner_joint" type="fixed">
    <parent link="bin_rack_center"/>
    <child link="bin_rack_top_back_right_corner"/>
    <origin rpy="0.0 0.0 0.0" xyz="${-bin_rack_width/2} ${bin_rack_length/2} 0 "/>
  </joint>
  <link name="bin_rack_top_back_right_corner"/>

  <joint name="bin_rack_top_back_left_corner_joint" type="fixed">
    <parent link="bin_rack_center"/>
    <child link="bin_rack_top_back_left_corner"/>
    <origin rpy="0.0 0.0 0.0" xyz="${-bin_rack_width/2} ${-bin_rack_length/2} 0 "/>
  </joint>
  <link name="bin_rack_top_back_left_corner"/>

  <joint name="bin_rack_top_front_left_corner_joint" type="fixed">
    <parent link="bin_rack_center"/>
    <child link="bin_rack_top_front_left_corner"/>
    <origin rpy="0.0 0.0 0.0" xyz="${bin_rack_width/2} ${-bin_rack_length/2} 0 "/>
  </joint>
  <link name="bin_rack_top_front_left_corner"/>

  <!-- add tray rack -->
  <xacro:o2as_box boxname="tray_rack" box_w="${tray_rack_width}" box_l="${tray_rack_length}" box_h="${tray_rack_height}" parent="workspace_center">
    <origin xyz="-.299 ${-tray_rack_length/2}  0" rpy="0 0 0" />
  </xacro:o2as_box>
  <link name="tray_rack_center" />
  <joint name="tray_rack_joint" type="fixed">
    <parent link="workspace_center" />
    <child link="tray_rack_center"/>
    <origin xyz="${-.299+tray_rack_width/2} 0 ${tray_rack_height}" rpy="0 0 0"/>
  </joint>

  <joint name="tray_rack_top_front_right_corner_joint" type="fixed">
    <parent link="tray_rack_center"/>
    <child link="tray_rack_top_front_right_corner"/>
    <origin rpy="0.0 0.0 0.0" xyz="${tray_rack_width/2} ${tray_rack_length/2} 0 "/>
  </joint>
  <link name="tray_rack_top_front_right_corner"/>

  <joint name="tray_rack_top_back_right_corner_joint" type="fixed">
    <parent link="tray_rack_center"/>
    <child link="tray_rack_top_back_right_corner"/>
    <origin rpy="0.0 0.0 0.0" xyz="${-tray_rack_width/2} ${tray_rack_length/2} 0 "/>
  </joint>
  <link name="tray_rack_top_back_right_corner"/>

  <joint name="tray_rack_top_back_left_corner_joint" type="fixed">
    <parent link="tray_rack_center"/>
    <child link="tray_rack_top_back_left_corner"/>
    <origin rpy="0.0 0.0 0.0" xyz="${-tray_rack_width/2} ${-tray_rack_length/2} 0 "/>
  </joint>
  <link name="tray_rack_top_back_left_corner"/>

  <joint name="tray_rack_top_front_left_corner_joint" type="fixed">
    <parent link="tray_rack_center"/>
    <child link="tray_rack_top_front_left_corner"/>
    <origin rpy="0.0 0.0 0.0" xyz="${tray_rack_width/2} ${-tray_rack_length/2} 0 "/>
  </joint>
  <link name="tray_rack_top_front_left_corner"/>

  <!-- add trays -->
  <!-- <xacro:kitting_tray1 trayname="set_1_tray_1" parent="tray_rack_center">
    <origin xyz="${-tray_rack_width/2} ${-tray_rack_length/2} 0" rpy="0 0 0" />
  </xacro:kitting_tray1>
  <xacro:kitting_tray2 trayname="set_1_tray_2" parent="tray_rack_center">
    <origin xyz="${-tray_rack_width/2} 0 0" rpy="0 0 0" />
  </xacro:kitting_tray2> -->
  <xacro:kitting_bin_3 binname="place_bin" parent="tray_rack_center" z_origin_offset="-.004">
    <origin xyz="0 0 0.004" rpy="0 0 -${pi/2}" />
  </xacro:kitting_bin_3>
</robot>
