<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
        name="aist_base_scene" >


  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="a_bot_x" value="0"/>
  <xacro:property name="a_bot_y" value="-0.4875"/>
  <!-- <xacro:property name="a_bot_theta" value="${pi}"/> -->
  <xacro:property name="b_bot_x" value="0"/>
  <xacro:property name="b_bot_y" value="0.4875"/>
  <xacro:property name="b_bot_theta" value="${pi}"/>

  <xacro:property name="bots_z" value="0.77"/>

  <!-- This is the main file defining our robot arrangement and physical environment. -->

  <!-- common stuff -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro" />
  <xacro:include filename="$(find aist_gazebo)/urdf/aist_base_scene.gazebo" />

  <!-- robots -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/ur5.urdf.xacro" />

  <!-- Scene items (trays, bins...) -->
  <!-- <xacro:include filename="$(find aist_scene_description)/urdf/aist_kitting_scene.xacro" /> -->

  <!-- Robot bases -->
  <!-- Putting these at height 0.0 makes them intersect with the ground, so they are elevated. -->
  <!-- There are some instabilities when the box is big, for some reason. -->
  <!-- <xacro:include filename="$(find aist_scene_description)/urdf/aist_base.xacro" /> -->
  <!-- <xacro:aist_base boxname="a_bot_base_smfl" parent="o2as_ground"> -->
    <!-- <origin xyz="${a_bot_x-0.225/2} ${a_bot_y-0.225/2} 0.72" rpy="0 0 0" /> -->
  <!-- </xacro:aist_base> -->
  <!-- <xacro:aist_base boxname="b_bot_base_smfl" parent="o2as_ground"> -->
    <!-- <origin xyz="${b_bot_x-0.225/2} ${b_bot_y-0.225/2} 0.72" rpy="0 0 0" /> -->
  <!-- </xacro:aist_base> -->

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/o2as_box.xacro"/>
  <xacro:property name="plate_w" value="0.9"/>
  <xacro:property name="plate_l" value="0.75"/>
  <xacro:property name="plate_h" value="0.01"/>
  <xacro:o2as_box boxname="workbox"
		  box_w="${plate_w}" box_l="${plate_l}" box_h="${plate_h}"
		  parent="o2as_ground">
    <origin xyz="${-plate_w/2} ${-plate_l/2} ${bots_z - plate_h}" rpy="0 0 0" />
  </xacro:o2as_box>
  <link name="workspace_center" />
  <joint name="world_to_workspace" type="fixed">
    <parent link="o2as_ground" />
    <child link="workspace_center" />
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0" />
  </joint>

  <!-- robot arms -->
  <xacro:ur5_robot prefix="a_bot_" joint_limited="false"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>

  <xacro:ur5_robot prefix="b_bot_" joint_limited="false"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>

  <link name="o2as_ground" />

  <joint name="world_a_bot_joint" type="fixed">
    <parent link="o2as_ground" />
    <child  link= "a_bot_base_link" />
    <origin xyz="${a_bot_x} ${a_bot_y} ${bots_z}" rpy="0 0 0" />
  </joint>

  <joint name="world_b_bot_joint" type="fixed">
    <parent link="o2as_ground" />
    <child  link= "b_bot_base_link" />
    <origin xyz="${b_bot_x} ${b_bot_y} ${bots_z}" rpy="0 0 ${b_bot_theta}" />
  </joint>

  <!-- Spawn and attach force sensor -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/ft300.urdf.xacro" />
  <xacro:ft300 prefix="a_bot_" parent="a_bot_ee_link" />
  <xacro:ft300 prefix="b_bot_" parent="b_bot_ee_link" />

  <!-- Spawn and attach gripper -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/robotiq_85_gripper_with_tip_link.urdf.xacro" />
  <xacro:robotiq_85_gripper_with_tip_link prefix="a_bot_"
					  parent="a_bot_ft300_frange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_85_gripper_with_tip_link>

  <xacro:include filename="$(find o2as_scene_description)/urdf/single_suction_gripper.urdf.xacro" />
  <xacro:single_suction_gripper_o2as prefix="b_bot_"
  				     parent="b_bot_ft300_frange_link">
    <origin xyz="0 0 0" rpy="0 ${0*pi/180} 0"/>
  </xacro:single_suction_gripper_o2as>

  <!-- Add virtual wall to avoid collisions-->
  <!-- <xacro:o2as_box boxname="table" box_w="0.9" box_l="0.75" box_h="0.01" parent="o2as_ground"> -->
  <!--   <origin xyz="-0.45 -0.375 ${bots_z}" rpy="0 0 0"/> -->
  <!-- </xacro:o2as_box> -->
  <xacro:o2as_box boxname="vwall1" box_w="0.01" box_l="0.5" box_h="0.6" parent="o2as_ground">
    <origin xyz="0.50 -0.25 ${bots_z}" rpy="0 0 0"/>
  </xacro:o2as_box>

  <!-- Add PhoXi 3D scanner -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/phoxi_m_camera.urdf.xacro" />
  <xacro:phoxi_m_camera prefix="a_" parent="o2as_ground">
    <origin xyz="0.533753808105 0.0 1.674786289459"
	    rpy="${-152.051675662*pi/180} ${1.32492983016*pi/180} ${88.0374935002*pi/180}"/>
    <!-- <origin xyz="0.679997723974 0.5 0.7" -->
    <!-- 	    rpy="${-143.76356757*pi/180} -->
    <!-- 		 ${0.312453823638*pi/180} ${85.5565266354*pi/180}"/> -->
  </xacro:phoxi_m_camera>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world" />
  <joint name="world_o2as_joint" type="fixed">
    <parent link="world" />
    <child link="o2as_ground" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>

</robot>
