<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="aist_box"
	       params="name width length height parent *origin">
    <!-- This creates a box with the origin in the bottom corner, fixed to the world link. -->

    <link name="${name}">
      <!-- w is in x, l is in y, h is in z -->
      <visual>
        <origin xyz="${width/2} ${length/2} ${height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${length} ${height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="1.0 1.0 1.0 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${width/2} ${length/2} ${height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${length} ${height}"/>
        </geometry>
      </collision>

      <!-- This is required for Gazebo. -->
      <inertial>
        <mass value="1.0" />
        <!-- <origin xyz="${width/2} ${length} ${height/2}" rpy="0 0 0"/> -->
        <inertia ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0"
          izz="0.0" />
      </inertial>
    </link>
    <gazebo reference="${name}">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${name}" type="fixed">
      <parent link="${parent}" />
      <child link = "${name}" />
      <xacro:insert_block name="origin"/>
    </joint>
  </xacro:macro>
</robot>
