<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
        name="dtorobo_base_scene" >


  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="a_torobo_x" value="0"/>
  <xacro:property name="a_torobo_y" value="-0.4875"/>
  <!-- <xacro:property name="a_torobo_theta" value="${pi}"/> -->
  <xacro:property name="b_torobo_x" value="0"/>
  <xacro:property name="b_torobo_y" value="0.4875"/>
  <xacro:property name="b_torobo_theta" value="${pi}"/>

  <xacro:property name="bots_z" value="0.785"/>

  <!-- common stuff -->
  <xacro:include filename="$(find aist_gazebo)/urdf/aist_base_scene.gazebo"/>

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <link name="o2as_ground"/>

  <xacro:include filename="$(find o2as_scene_description)/urdf/o2as_box.xacro"/>
  <xacro:property name="table_w" value="0.9"/>
  <xacro:property name="table_l" value="0.75"/>
  <xacro:property name="table_h" value="0.01"/>
  <xacro:o2as_box boxname="workbox"
		  box_w="${table_w}" box_l="${table_l}" box_h="${table_h}"
		  parent="o2as_ground">
    <origin xyz="${-table_w/2} ${-table_l/2} ${bots_z - table_h}" rpy="0 0 0"/>
  </xacro:o2as_box>
  <link name="workspace_center"/>
  <joint name="world_to_workspace" type="fixed">
    <parent link="o2as_ground"/>
    <child link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- robot arms -->
  <xacro:include filename="$(find aist_scene_description)/urdf/torobo_arm.urdf.xacro"/>
  <xacro:torobo_arm_gripper prefix="a_torobo"/>
  <joint name="world_a_torobo_joint" type="fixed">
    <parent link="o2as_ground"/>
    <child  link= "a_torobo/base"/>
    <origin xyz="${a_torobo_x} ${a_torobo_y} ${bots_z}" rpy="0 0 0"/>
  </joint>

  <xacro:torobo_arm_gripper prefix="b_torobo"/>
  <joint name="world_b_torobo_joint" type="fixed">
    <parent link="o2as_ground"/>
    <child  link= "b_torobo/base"/>
    <origin xyz="${b_torobo_x} ${b_torobo_y} ${bots_z}"
	    rpy="0 0 ${b_torobo_theta}"/>
  </joint>

  <!-- Add PhoXi 3D scanner -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/phoxi_m_camera.urdf.xacro"/>
  <xacro:phoxi_m_camera prefix="b_" parent="o2as_ground">
    <origin xyz="0.547941636523
		 -0.00827443204237
		 1.67030171767"
	    rpy="${-151.493605482*pi/180}
		 ${0.698490882792*pi/180}
		 ${85.0482907121*pi/180}"/>
  </xacro:phoxi_m_camera>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world"/>
  <joint name="world_o2as_joint" type="fixed">
    <parent link="world"/>
    <child link="o2as_ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
