<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pgrp_kitting">
  <xacro:include filename="$(find aist_scene_description)/urdf/pgrp_base_scene.urdf.xacro" />

  <xacro:property name="board_length" value="0.68"/>
  <xacro:property name="board_width"  value="0.42"/>
  <xacro:property name="board_height" value="0.015"/>

  <!-- front board -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/o2as_box.xacro"/>
  <xacro:o2as_box boxname="board"
		  box_w="${board_length}"
		  box_l="${board_width}"
		  box_h="${board_height}"
		  parent="workspace_center">
    <origin xyz="${-board_length/2} ${-board_width/2} ${-borad_height/2}"
	    rpy="0 0 0"/>
  </xacro:o2as_box>
  <link name="board_center"/>
  <joint name="workspace_to_board" type="fixed">
    <parent link="workspace_center"/>
    <child  link="board_center"/>
    <origin xyz="0 0 ${board_height}" rpy="0 0 0"/>
  </joint>

  <!-- bin1_definition -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/kitting_bin_macros.xacro" />
  <xacro:property name="bin_1_width"		value="0.125"/>
  <xacro:property name="bin_1_length"		value="0.128"/>
  <xacro:property name="z_origin_offset_1"	value="-.005" />

  <!-- bin2_definition -->
  <xacro:property name="bin_2_width"		value="0.112"/>
  <xacro:property name="bin_2_length"		value="0.201"/>
  <xacro:property name="z_origin_offset_2"	value="-.008" />

  <!-- bin3_definition -->
  <xacro:property name="bin_3_width"		value="0.192"/>
  <xacro:property name="bin_3_length"		value="0.285"/>
  <xacro:property name="z_origin_offset_3"	value="-.004" />

  <!-- A row of bin1 -->
  <xacro:property name="set1_x"	value="0"/>
  <xacro:property name="set1_y" value="0.096"/>
  <xacro:property name="set1_z" value="0"/>
  <!-- A row of bin2 -->
  <xacro:property name="set2_x" value="0.25"/>
  <xacro:property name="set2_y" value="0.096"/>
  <xacro:property name="set2_z" value="0"/>

  <!--bin_2_part_4_-->
  <xacro:kitting_bin_2 binname	      ="bin_2_part_4"
		       parent	      ="board_center"
		       z_origin_offset="-0.008">
    <origin xyz="0.100  0 0.004" rpy="0 0 0" />
  </xacro:kitting_bin_2>
  <!--bin_2_part_7_-->
  <xacro:kitting_bin_2 binname	      ="bin_2_part_7"
		       parent	      ="board_center"
		       z_origin_offset="-0.008">
    <origin xyz="0.100 0.112 0.008" rpy="0 0 0" />
  </xacro:kitting_bin_2>
  <!--bin_2_part_8_-->
  <xacro:kitting_bin_2 binname	      ="bin_2_part_8"
  		       parent	      ="board_center"
  		       z_origin_offset="-0.008">
    <origin xyz="0.100 -0.112 0.008" rpy="0 0 0" />
  </xacro:kitting_bin_2>

  <!-- bin_3_part_15_ -->
  <xacro:kitting_bin_3 binname	      ="bin_3_part_15"
  		       parent	      ="board_center"
  		       z_origin_offset="-0.004">
    <origin xyz="-0.143 0.096 0.004" rpy="0 0 0" />
  </xacro:kitting_bin_3>
  <!-- bin_3_part_16_ -->
  <xacro:kitting_bin_3 binname	      ="bin_3_part_16"
  		       parent	      ="board_center"
  		       z_origin_offset="-0.004">
    <origin xyz="-0.143 -0.096 0.004" rpy="0 0 0" />
  </xacro:kitting_bin_3>

  <xacro:include filename="$(find aist_scene_description)/urdf/kitting_tray_with_partitions.xacro" />
  <xacro:kitting_tray1 trayname="tray_1" parent="board_center">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:kitting_tray1>
  <xacro:kitting_tray2 trayname="tray_2" parent="board_center">
    <origin xyz="0 ${-tray_width - 0.002} 0" rpy="0 0 0" />
  </xacro:kitting_tray2>

</robot>
