<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
        name="pgrp_base_scene" >


  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="a_bot_x" value="0"/>
  <xacro:property name="a_bot_y" value="-0.4875"/>
  <!-- <xacro:property name="a_bot_theta" value="${pi}"/> -->
  <xacro:property name="b_bot_x" value="0"/>
  <xacro:property name="b_bot_y" value="0.4875"/>
  <xacro:property name="b_bot_theta" value="${pi}"/>

  <xacro:property name="bots_z" value="0.77"/>

  <!-- This is the main file defining our robot arrangement and physical environment. -->

  <!-- common stuff -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro"/>
  <xacro:include filename="$(find aist_gazebo)/urdf/aist_base_scene.gazebo"/>

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <link name="o2as_ground"/>

  <xacro:include filename="$(find o2as_scene_description)/urdf/o2as_box.xacro"/>
  <xacro:property name="plate_w" value="0.9"/>
  <xacro:property name="plate_l" value="0.75"/>
  <xacro:property name="plate_h" value="0.01"/>
  <xacro:o2as_box boxname="workbox"
		  box_w="${plate_w}" box_l="${plate_l}" box_h="${plate_h}"
		  parent="o2as_ground">
    <origin xyz="${-plate_w/2} ${-plate_l/2} ${bots_z - plate_h}" rpy="0 0 0"/>
  </xacro:o2as_box>
  <link name="workspace_center"/>
  <joint name="world_to_workspace" type="fixed">
    <parent link="o2as_ground"/>
    <child link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- robot arms -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/ur5.urdf.xacro"/>
  <xacro:ur5_robot prefix="a_bot_" joint_limited="false"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>

  <xacro:ur5_robot prefix="b_bot_" joint_limited="false"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>

  <joint name="world_a_bot_joint" type="fixed">
    <parent link="o2as_ground"/>
    <child  link= "a_bot_base_link"/>
    <origin xyz="${a_bot_x} ${a_bot_y} ${bots_z}" rpy="0 0 0"/>
  </joint>

  <joint name="world_b_bot_joint" type="fixed">
    <parent link="o2as_ground"/>
    <child  link= "b_bot_base_link"/>
    <origin xyz="${b_bot_x} ${b_bot_y} ${bots_z}" rpy="0 0 ${b_bot_theta}"/>
  </joint>

  <!-- Spawn and attach force sensor -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/ft300.urdf.xacro"/>
  <xacro:ft300 prefix="a_bot_" parent="a_bot_ee_link"/>
  <xacro:ft300 prefix="b_bot_" parent="b_bot_ee_link"/>

  <!-- Spawn and attach gripper -->
  <xacro:include filename="$(find aist_scene_description)/urdf/InnerOnlyGripper.urdf.xacro" />
  <xacro:InnerOnlyGripper prefix="a_bot_"  grippername = "gripper" parent = "a_bot_ft300_frange_link">
    <origin xyz="0 0 0" rpy="${-pi/2} ${-1.3*pi/180} ${0.4*pi/180}"/>
  </xacro:InnerOnlyGripper>

  <xacro:include filename="$(find o2as_scene_description)/urdf/single_suction_gripper.urdf.xacro"/>
  <xacro:single_suction_gripper_o2as prefix="b_bot_"
  				     parent="b_bot_ft300_frange_link">
    <origin xyz="0 0 0" rpy="0 ${0.8*pi/180} ${-0.5*pi/180}"/>
  </xacro:single_suction_gripper_o2as>

  <!-- Add virtual wall to avoid collisions-->
  <!-- <xacro:o2as_box boxname="vwall1" box_w="0.01" box_l="0.5" box_h="0.6" parent="o2as_ground"> -->
  <!--   <origin xyz="0.50 -0.25 ${bots_z}" rpy="0 0 0"/> -->
  <!-- </xacro:o2as_box> -->

  <!-- Add PhoXi 3D scanner -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/phoxi_m_camera.urdf.xacro"/>
  <xacro:phoxi_m_camera prefix="a_" parent="o2as_ground">
    <origin xyz="0.547941636523
		 -0.00827443204237
		 1.67030171767"
	    rpy="${-151.493605482*pi/180}
		 ${0.698490882792*pi/180}
		 ${85.0482907121*pi/180}"/>
  </xacro:phoxi_m_camera>

  <!-- Add RealSense camerar -->
  <xacro:include filename="$(find o2as_realsense2_camera)/urdf/_d435.urdf.xacro" />
  <link name="a_bot_cam_holder_link" />
  <joint name="a_bot_cam_holder_joint" type="fixed">
    <parent link="a_bot_wrist_2_link" />
    <child  link="a_bot_cam_holder_link" />
    <origin xyz="0.0 -0.06 0.20" rpy="${0*pi/180} 0.0 ${pi/2}" />
  </joint>
  <xacro:sensor_d435 prefix="a_bot_" parent="a_bot_cam_holder_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:sensor_d435>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world"/>
  <joint name="world_o2as_joint" type="fixed">
    <parent link="world"/>
    <child link="o2as_ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
