<?xml version="1.0"?>

<!-- This macro adds a convenient TF frame at the tip of the closed gripper. -->
<!-- The position of the TF frame has not been measured at all and needs to be calibrated. -->

<robot name="single_suction_gripper_o2as" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- This seems too long when measuring the sensor,
       but works out when calibrating the tip_link to the world. -->
  <xacro:property name="ft300_length" value="0.0360"/>

  <xacro:macro name="single_suction_gripper_with_ft300" params="prefix parent">
    <!-- Add the force sensor in front of the gripper. -->
    <joint name="${prefix}ft300_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}ft300_link"/>
      <origin rpy="0.0 ${pi/2} 0.0" xyz="${ft300_length/2} 0.0 0.0"/>
    </joint>
    <link name="${prefix}ft300_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${ft300_length}" radius="0.0375"/>
        </geometry>
        <material name="Black">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
    </link>

    <xacro:include filename="$(find o2as_scene_description)/urdf/single_suction_gripper.urdf.xacro" />

    <xacro:single_suction_gripper_o2as prefix="${prefix}" parent="${parent}">
        <origin rpy="0.0 0.0 0.0" xyz="${ft300_length} 0.0 0.0"/>
    </xacro:single_suction_gripper_o2as>

  </xacro:macro>
</robot>
