<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       name="table">

  <xacro:include filename="$(find aist_scene_description)/urdf/aist_box.urdf.xacro"/>
  <xacro:include filename="$(find aist_scene_description)/urdf/aist_floating_box.urdf.xacro"/>

  <xacro:macro name="tray"
	       params="prefix width length height parent *origin">

    <xacro:property name="tray_thickness"	value="0.005" />

    <xacro:aist_floating_box name="${prefix}tray"
			     width="${width}"
			     length="${length}"
			     height="${tray_thickness}"
			     parent="${parent}">
      <xacro:insert_block name="origin"/>
    </xacro:aist_floating_box>

    <xacro:aist_box name="${prefix}tray_wall0"
		    width="${width}"
		    length="${tray_thickness}"
		    height="${height - tray_thickness}"
		    parent="${prefix}tray">
      <origin xyz="0 0 ${tray_thickness}" rpy="0 0 0"/>
    </xacro:aist_box>

    <xacro:aist_box name="${prefix}tray_wall1"
		    width="${tray_thickness}"
		    length="${length - 2*tray_thickness}"
		    height="${height - tray_thickness}"
		    parent="${prefix}tray">
      <origin xyz="0 ${tray_thickness} ${tray_thickness}" rpy="0 0 0"/>
    </xacro:aist_box>

    <xacro:aist_box name="${prefix}tray_wall2"
		    width="${width}"
		    length="${tray_thickness}"
		    height="${height - tray_thickness}"
		    parent="${prefix}tray">
      <origin xyz="0 ${length - tray_thickness} ${tray_thickness}" rpy="0 0 0"/>
    </xacro:aist_box>

    <xacro:aist_box name="${prefix}tray_wall3"
		    width="${tray_thickness}"
		    length="${length - 2*tray_thickness}"
		    height="${height - tray_thickness}"
		    parent="${prefix}tray">
      <origin xyz="${width - tray_thickness} ${tray_thickness} ${tray_thickness}"
	      rpy="0 0 0"/>
    </xacro:aist_box>

    <xacro:macro name="auxiliary_frame" params="parent framename *origin">
      <joint name="${parent}_${framename}" type="fixed">
	<parent link="${parent}" />
	<child link = "${parent}_${framename}"/>
	<xacro:insert_block name="origin"/>
      </joint>
      <link name="${parent}_${framename}"/>
    </xacro:macro>

    <xacro:auxiliary_frame parent="${prefix}tray" framename="origin">
      <origin xyz="${tray_thickness} ${tray_thickness} ${tray_thickness}"
	      rpy="0 0 0"/>
    </xacro:auxiliary_frame>

    <xacro:auxiliary_frame parent="${prefix}tray_origin" framename="center">
      <origin xyz="${width/2 - tray_thickness} ${length/2 - tray_thickness} 0"
	      rpy="0 0 0"/>
    </xacro:auxiliary_frame>

  </xacro:macro>
</robot>
