camera_type: DepthCamera
camera_name: realsenseD435
robot_name: c_bot
eye_on_hand: false
robot_base_frame: workspace_center
robot_effector_frame: c_bot_ee_link
camera_frame: calibrated_realsenseD435_color_optical_frame
marker_id: 26
marker_size: 0.07
planarity_tolerance: 0.008
initpose: [0.00, 0.05, 0.30, -90, 90, 0]
keyposes:
  - [-0.15,  0.20, 0.25, 30, 30, 90]
  - [-0.15,  0.10, 0.25, 30, 30, 90]
#  - [-0.15,  0.00, 0.25, 30, 30, 90]

  - [0.00,  0.20, 0.25, 30, 30, 90]
  - [0.00,  0.10, 0.25, 30, 30, 90]
#  - [0.00,  0.00, 0.25, 30, 30, 90]

#  - [0.15,  0.20, 0.25, 30, 30, 90]
  - [0.15,  0.10, 0.25, 30, 30, 90]
#  - [0.15,  0.00, 0.25, 30, 30, 90]

camera_body_frame: realsenseD435_link
camera_optical_frame: realsenseD435_color_optical_frame
