controller_list:
  - name: fake_c_bot_controller
    joints:
      - c_bot_shoulder_pan_joint
      - c_bot_shoulder_lift_joint
      - c_bot_elbow_joint
      - c_bot_wrist_1_joint
      - c_bot_wrist_2_joint
      - c_bot_wrist_3_joint
  - name: fake_d_bot_controller
    joints:
      - d_bot_shoulder_pan_joint
      - d_bot_shoulder_lift_joint
      - d_bot_elbow_joint
      - d_bot_wrist_1_joint
      - d_bot_wrist_2_joint
      - d_bot_wrist_3_joint
  - name: fake_all_bots_controller
    joints:
      - c_bot_shoulder_pan_joint
      - c_bot_shoulder_lift_joint
      - c_bot_elbow_joint
      - c_bot_wrist_1_joint
      - c_bot_wrist_2_joint
      - c_bot_wrist_3_joint
      - d_bot_shoulder_pan_joint
      - d_bot_shoulder_lift_joint
      - d_bot_elbow_joint
      - d_bot_wrist_1_joint
      - d_bot_wrist_2_joint
      - d_bot_wrist_3_joint