<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="kitting_scene">
  <xacro:include filename="$(find o2as_scene_description)/urdf/kitting_bin.xacro" />
  
  <xacro:property name="bin_width" value=".15"/>

  <!-- A few arranged bins -->
  <xacro:property name="set1_x" value=".15"/>
  <xacro:property name="set1_y" value="0"/>
  <xacro:property name="set1_z" value=".95"/>

  <xacro:kitting_bin binname="set1_bin1">
    <origin xyz="${set1_x} ${set1_y} ${set1_z}" rpy="0 0 0" />   
  </xacro:kitting_bin>
  <xacro:kitting_bin binname="set1_bin2">
    <origin xyz="${set1_x} ${set1_y + bin_width*1} ${set1_z}" rpy="0 0 0" />   
  </xacro:kitting_bin>
  <xacro:kitting_bin binname="set1_bin3">
    <origin xyz="${set1_x} ${set1_y + bin_width*2} ${set1_z}" rpy="0 0 0" />   
  </xacro:kitting_bin>

  <xacro:property name="set2_x" value=".25"/>
  <xacro:property name="set2_y" value="0"/>
  <xacro:property name="set2_z" value=".85"/>
  
</robot> 