<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="kitting_scene">
  <!-- <xacro:include filename="$(find o2as_scene_description)/urdf/kitting_bins.xacro" /> -->
  <!-- <xacro:include filename="$(find o2as_scene_description)/urdf/kitting_tray_with_partitions.xacro" /> -->
  <xacro:include filename="$(find realsense2_camera)/urdf/_d435.urdf.xacro" />

  <!-- spawn and attach dual suction grippers -->
  <!-- <xacro:include filename="$(find o2as_scene_description)/urdf/dual_suction_gripper.urdf.xacro" /> -->
  <!-- <xacro:dual_suction_gripper_o2as prefix="b_bot_" parent = "b_bot_ee_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:dual_suction_gripper_o2as> -->

  <xacro:property name="tray_width" value=".300" />
  <xacro:property name="tray_length" value=".210" />

  <!-- add camera for pose matching on the table -->
  <link name="workspace_cam_holder_link" />
  <joint name="workspace_cam_holder_joint" type="fixed">
    <parent link="workspace_center" />
    <child  link="workspace_cam_holder_link" />
    <origin xyz="0 0 0" rpy="0.0 -${pi/2} 0.0" />
  </joint>
  <xacro:sensor_d435 prefix="workspace_" parent="workspace_cam_holder_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:sensor_d435>
  <!-- TODO: Deal with this camera? -->

  <!-- A row of tray -->
  <!-- <xacro:property name="set3_x" value="${-.3}" />
  <xacro:property name="set3_y" value="${0}" />
  <xacro:property name="set3_z" value=".00" />

  <xacro:kitting_tray1 trayname="set3_tray_1" parent="workspace_center">
    <origin xyz="${set3_x} ${set3_y} ${set3_z}" rpy="0 0 0" />
  </xacro:kitting_tray1>
  <xacro:kitting_tray2 trayname="set3_tray_2" parent="workspace_center">
    <origin xyz="${set3_x} ${set3_y-tray_width} ${set3_z}" rpy="0 0 0" />
  </xacro:kitting_tray2> -->
  
</robot>
