grippers:
  a_bot:
#    type: GenericGripper
#    args:
#      name: a_bot_robotiq_85_gripper
#      action_ns: /a_bot_robotiq_85_controller/gripper_cmd
#      base_link: a_bot_robotiq_85_base_link
#      tip_link: a_bot_robotiq_85_tip_link
#      timeout: 10.0
#      min_gap: 0.0
#      max_gap: 1.0
#      max_effort: 5.0
    type: RobotiqGripper
    args:
      prefix: a_bot_
      product: robotiq_85
      force: 5.0
      velocity: 0.1
      timeout: 6.0
  b_bot:
    type: SuctionGripper
    args:
      name: b_bot_single_suction_gripper
      base_link: b_bot_single_suction_gripper_base_link
      tip_link: b_bot_single_suction_gripper_pad_link
      eject: false
      timeout: 2.0

cameras:
  a_phoxi_m_camera: PhoXiCamera
  a_bot_inside_camera: RealSenseCamera
  a_bot_outside_camera: RealSenseCamera
