groups:
  - a_bot
  - b_bot
  - all_bots

grippers:
  a_bot:
    type: RobotiqGripper
    args:
      prefix: a_bot_
      product: "85"
      force: 5.0
      velocity: 0.1
  b_bot:
    type: SuctionGripper
    args:
      prefix: b_bot_single_
      eject: false

cameras:
  a_phoxi_m_camera:
    type: PhoXiCamera
    args:
      name: a_phoxi_m_camera
  a_bot_camera:
    type: DepthCamera
    args:
      name: a_bot_camera
