grippers:
  arm:
    type: GenericGripper
    args:
      name: gripper
      action_ns: gripper_controller/gripper_action
      base_link: wrist_roll_link
      tip_link: gripper_link
      timeout: 10.0
      min_gap: 0.0
      max_gap: 0.1
      max_effort: 0.0

cameras:
  head_camera:
    type: DepthCamera
    args:
      name: head_camera
      camera_info_topic: depth/camera_info
      image_topic: rgb/image_rect_color
      pointcloud_topic: depth/point
      depth_topic: depth/image_rect

moveit_pose_reference_frame: "base_link"
moveit_eef_step: 0.05
