groups:
  - arm
  - gripper

grippers:
  arm:
    type: FetchGripper
    args:
      prefix: ""
      max_effort: 5.0

cameras:
  head_camera:
    type: DepthCamera
    args:
      name: head_camera

moveit_pose_reference_frame: "base_link"
moveit_eef_step: 0.05
