grippers:
  a_torobo:
    type: ToroboGripper
    args:
      prefix: a_torobo_
      max_effort: 5.0
  b_torobo:
    type: ToroboGripper
    args:
      prefix: b_torobo_
      max_effort: 5.0

cameras:
  b_phoxi_m_camera:
    type: PhoXiCamera
    args:
      name: b_phoxi_m_camera
