torobo_controller_config:
  a_torobo_arm_gripper_controller:
    # Connection type (USB or Ethernet)
    - connection_type: USB
    # - connection_type: Ethernet

    # Ethernet connection config
    - ethernet: {
        master_controller_ip: 10.66.171.61,
        master_controller_port: 50000
      }

    # Serial Port connection config
    - serial_port: {
        master_controller_device_name: /dev/ttyUSB0,
        master_controller_baudrate: 3000000
      }

    # controller definitions
    - controller_name: a_torobo_arm_controller
    - controller_name: a_torobo_gripper_controller

  b_torobo_arm_gripper_controller:
    # Connection type (USB or Ethernet)
    - connection_type: USB
    # - connection_type: Ethernet

    # Ethernet connection config
    - ethernet: {
        master_controller_ip: 10.66.171.62,
        master_controller_port: 50010
      }

    # Serial Port connection config
    - serial_port: {
        master_controller_device_name: /dev/ttyUSB1,
        master_controller_baudrate: 3000000
      }

    # controller definitions
    - controller_name: b_torobo_arm_controller
    - controller_name: b_torobo_gripper_controller
