robots:
  d_bot:
    default_gripper: d_bot_robotiq_hande_gripper

grippers:
  d_bot_robotiq_hande_gripper:
    type: RobotiqGripper
    args:
      prefix: d_bot_
      product: robotiq_hande
      force: 5.0
      velocity: 0.1
      timeout: 6.0
