robots:
  c_bot:
    default_gripper: c_bot_robotiq_85_gripper

grippers:
  c_bot_robotiq_85_gripper:
    type: RobotiqGripper
    args:
      prefix: c_bot_
      product: robotiq_85
      force: 5.0
      velocity: 0.1
      timeout: 6.0

cameras:
  realsenseD435: DepthCamera
