grippers:
  a_bot:
    class: PrecisionGripper
    args:
      prefix: a_bot_
      timeout: 3.0
  b_bot:
    class: SuctionGripper
    args:
      prefix: b_bot_single_
      eject: false
      timeout: 2.0

cameras:
  a_phoxi_m_camera:
    class: PhoXiCamera
    args:
      name: a_phoxi_m_camera
  a_bot_camera:
    class: RealsenseCamera
    args:
      name: a_bot_camera
