groups:
  - a_bot
  - b_bot
  - all_bots

grippers:
  a_bot:
    type: PrecisionGripper
    args:
      prefix: a_bot_
  b_bot:
    type: SuctionGripper
    args:
      prefix: b_bot_single_
      eject: false

cameras:
  a_phoxi_m_camera:
    type: PhoXiCamera
    args:
      name: a_phoxi_m_camera
  a_bot_camera:
    type: DepthCamera
    args:
      name: a_bot_camera

ftsensor:
  a_bot:
    thresholds:
      force:
        min: [ -5, -5, -5 ]
        max: [ 10, 10, 10 ]
  b_bot:
    thresholds:
      force:
        min: [ -5, -5, -10 ]
        max: [ 10, 10, 10 ]
