grippers:
  a_bot:
    type: PrecisionGripper
    args:
      prefix: a_bot_
      timeout: 3.0
  b_bot:
    type: SuctionGripper
    args:
      name: b_bot_single_suction_gripper
      base_link: b_bot_single_suction_gripper_base_link
      tip_link: b_bot_single_suction_gripper_pad_link
      eject: false
      timeout: 2.0

cameras:
  a_phoxi_m_camera:
    type: PhoXiCamera
    args:
      name: a_phoxi_m_camera
  a_bot_camera:
    type: DepthCamera
    args:
      name: a_bot_camera
      camera_info_topic: color/camera_info
      image_topic: color/image_raw
      pointcloud_topic: depth/color/point
      depth_topic: aligned_depth_to_color/image_raw

ftsensor:
  a_bot:
    thresholds:
      force:
        min: [ -5, -5, -5 ]
        max: [ 10, 10, 10 ]
  b_bot:
    thresholds:
      force:
        min: [ -5, -5, -10 ]
        max: [ 10, 10, 10 ]
