robots:
  b_torobo:
    default_gripper: b_torobo_gripper

grippers:
  b_torobo_gripper:
    type: VoidGripper
    args:
      name: b_torobo_gripper
      base_link: b_torobo_arm/ee_link
      timeout: 10.0
