robots:
  arm:
    default_gripper: magnet

grippers:
  magnet:
    type: MagswitchGripper
    args:
      prefix: ''
      timeout: 2.5
  gripper:
    type: Lecp6Gripper
    args:
      prefix: ''
      timeout: 2.0

cameras:
  camera: PhoXiCamera

moveit_pose_reference_frame: base_link
moveit_eef_step: 0.05
