robots:
  a_bot:
    default_gripper: a_bot_robotiq_140_gripper

grippers:
  a_bot_robotiq_140_gripper:
    type: RobotiqGripper
    args:
      prefix: a_bot_
      product: robotiq_140
      force: 5.0
      velocity: 0.1
      timeout: 6.0

cameras:
  a_bot_camera: DepthCamera
