groups:
  - c_bot
  - d_bot
  - all_bots

grippers:
  c_bot:
    type: RobotiqGripper
    args:
      prefix: c_bot_
      product: "85"
      force: 5.0
      velocity: 0.1
  d_bot:
    type: RobotiqGripper
    args:
      prefix: d_bot_
      product: hande
      force: 5.0
      velocity: 0.1
