grippers:
  c_bot:
    type: Robotiq85Gripper
    args:
      prefix: c_bot_
      force: 5.0
      velocity: 0.1
      timeout: 6.0
  d_bot:
    type: Robotiq85Gripper
    args:
      prefix: d_bot_
      force: 5.0
      velocity: 0.1
      timeout: 6.0
