grippers:
  c_bot:
    type: RobotiqGripper
    args:
      prefix: c_bot_
      product: robotiq_85
      force: 5.0
      velocity: 0.1
      timeout: 6.0
  d_bot:
    type: RobotiqGripper
    args:
      prefix: d_bot_
      product: robotiq_hande
      force: 5.0
      velocity: 0.1
      timeout: 6.0
