camera_name: a_bot_inside_camera
robot_name: a_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: a_bot_ee_link
camera_frame: a_bot_inside_camera_color_optical_frame_calibrated
initpose: [0.00, -0.20, 0.35, -90, 90, 0]
keyposes:
  - [-0.15, -0.10, 0.40, -90,  60,  0]
  - [-0.10, -0.08, 0.40, -90,  75,  0]
  - [-0.05, -0.08, 0.40, -90,  90,  0]
  - [-0.00, -0.06, 0.40, -90, 100,  0]
  - [ 0.05, -0.04, 0.40, -90, 110,  0]
  - [-0.05, -0.20, 0.40,   0,  70, 90]
  - [-0.05, -0.12, 0.40,   0,  80, 90]
  - [-0.05,  0.00, 0.40,   0, 100, 90]
  - [-0.05,  0.08, 0.40,   0, 110, 90]

camera_body_frame: a_bot_inside_camera_link
camera_optical_frame: a_bot_inside_camera_color_optical_frame
