# z-axis points into the hole
geometry_msgs/PoseStamped target_hole  # If 0, the insertion is started without moving to the target
float64 maximum_insertion_distance
string gripper
---
# Result
bool success
---
# Feedback
float32 progress
