bool use_complex_planning           # Use simple grasp planning from above or complex planning?
bool do_complex_pick_from_inside    # First positions with the inner gripper, then grasps with outer
bool do_complex_pick_from_outside   # First positions with the inner gripper, then grasps with outer
bool retreat_after_pick             # If true, arm moves away from the table after grasping
string item_id                      # item ID in the planning scene
geometry_msgs/PoseStamped item_pose # This overrides the item_id
string robot_name                   # "a_bot", "b_bot", "c_bot"
string tool_name                    # "outer_gripper", "inner_gripper", "suction", "screw_tool" or empty
uint8 screw_size                    # M4, M5, M6 (without the M)
---
# success
bool success
---
# Feedback
float32 progress 
