# This should be called when? To say screw this frame into this other frame? Or when the screw is positioned? Probably the former.


# Request
# z points into the screw hole
geometry_msgs/PoseStamped target_hole
string gripper
---
# Result
bool success
---
# Feedback
float32 progress