controller_list:
  - name: fake_c_bot_controller
    joints:
      - c_bot_shoulder_pan_joint
      - c_bot_shoulder_lift_joint
      - c_bot_elbow_joint
      - c_bot_wrist_1_joint
      - c_bot_wrist_2_joint
      - c_bot_wrist_3_joint