<?xml version="1.0" ?>

<robot name="ar_marker" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="ar_marker" params="marker_id size thickness
					prefix parent *origin">

    <joint name="${prefix}ar_marker_joint" type="fixed">
      <parent link="${parent}" />
      <child link = "${prefix}ar_marker" />
      <xacro:insert_block name="origin" />
    </joint>

    <link name="${prefix}ar_marker">
      <visual name="${prefix}ar_marker_visual">
	<origin xyz="0 0 ${-thickness/2}" rpy="0 0 ${pi}"/>
        <geometry>
          <box size="${size} ${size} ${thickness}" />
        </geometry>
        <!--<material name="orange" />-->
      </visual>
      <collision name="${prefix}ar_marker_collision">
	<origin xyz="0 0 ${-thickness/2}" rpy="0 0 ${pi}"/>
        <geometry>
          <box size="${size} ${size} ${thickness}" />
        </geometry>
      </collision>
    </link>

    <!-- For Gazebo, material of AR marker is defined in
         gazebo/media/material. You also need to export
         gazebo_media_path in package.xml. -->
    <gazebo reference="${prefix}ar_marker">
      <material>Aruco/marker${marker_id}</material>
    </gazebo>

  </xacro:macro>

</robot>
