controller_list:
  - action_ns: follow_joint_trajectory
    default: true
    joints:
      - a_torobo_arm/joint_1
      - a_torobo_arm/joint_2
      - a_torobo_arm/joint_3
      - a_torobo_arm/joint_4
      - a_torobo_arm/joint_5
      - a_torobo_arm/joint_6
      - a_torobo_arm/joint_7
    name: a_torobo_arm_controller
    type: FollowJointTrajectory

  - action_ns: gripper_cmd
    default: true
    joints:
      - a_torobo_gripper/finger_joint
    name: a_torobo_gripper_controller
    type: GripperCommand

  - action_ns: follow_joint_trajectory
    default: true
    joints:
      - b_torobo_arm/joint_1
      - b_torobo_arm/joint_2
      - b_torobo_arm/joint_3
      - b_torobo_arm/joint_4
      - b_torobo_arm/joint_5
      - b_torobo_arm/joint_6
      - b_torobo_arm/joint_7
    name: b_torobo_arm_controller
    type: FollowJointTrajectory

  - action_ns: gripper_cmd
    default: true
    joints:
      - b_torobo_gripper/finger_joint
    name: b_torobo_gripper_controller
    type: GripperCommand
