controller_list:
  - name: fake_a_torobo_controller
    joints:
      - a_torobo/arm/joint_1
      - a_torobo/arm/joint_2
      - a_torobo/arm/joint_3
      - a_torobo/arm/joint_4
      - a_torobo/arm/joint_5
      - a_torobo/arm/joint_6
  - name: fake_b_torobo_controller
    joints:
      - b_torobo/arm/joint_1
      - b_torobo/arm/joint_2
      - b_torobo/arm/joint_3
      - b_torobo/arm/joint_4
      - b_torobo/arm/joint_5
      - b_torobo/arm/joint_6