controller_list:
  - name: b_bot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - b_bot_shoulder_pan_joint
      - b_bot_shoulder_lift_joint
      - b_bot_elbow_joint
      - b_bot_wrist_1_joint
      - b_bot_wrist_2_joint
      - b_bot_wrist_3_joint
