controller_list:
  - name: c_bot_fake_controller
    joints:
      - c_bot_shoulder_pan_joint
      - c_bot_shoulder_lift_joint
      - c_bot_elbow_joint
      - c_bot_wrist_1_joint
      - c_bot_wrist_2_joint
      - c_bot_wrist_3_joint
  - name: d_bot_fake_controller
    joints:
      - d_bot_shoulder_pan_joint
      - d_bot_shoulder_lift_joint
      - d_bot_elbow_joint
      - d_bot_wrist_1_joint
      - d_bot_wrist_2_joint
      - d_bot_wrist_3_joint

initial:
  - group: "c_bot"
    pose: "home"
  - group: "d_bot"
    pose: "home"
