hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - a_iiwa_robotiq_85_left_knuckle_joint
  constraints:
    goal_time: 0.5
  state_publish_rate:  25
  action_monitor_rate: 30
  stop_trajectory_duration: 0.5

