bh_j11_position_controller:
  type: position_controllers/JointPositionController
  joint: b_iiwa_bh_j11_joint
bh_j12_position_controller:
  type: position_controllers/JointPositionController
  joint: b_iiwa_bh_j12_joint
bh_j22_position_controller:
  type: position_controllers/JointPositionController
  joint: b_iiwa_bh_j22_joint
bh_j32_position_controller:
  type: position_controllers/JointPositionController
  joint: b_iiwa_bh_j32_joint

hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - b_iiwa_bh_j11_joint
    - b_iiwa_bh_j12_joint
    - b_iiwa_bh_j22_joint
    - b_iiwa_bh_j32_joint
  constraints:
    goal_time: 0.5
  state_publish_rate:  25
  action_monitor_rate: 30
  stop_trajectory_duration: 0.5

