$(arg prefix)arm_gripper_controller:
  # Connection type (USB or Ethernet)
  # - connection_type: USB
  - connection_type: Ethernet

  # Ethernet connection config
  - ethernet: {
      master_controller_ip: $(arg ip)
      master_controller_port: $(arg port)
    }

  # Serial Port connection config
  - serial_port: {
      master_controller_device_name: /dev/ttyUSB0,
      master_controller_baudrate: 3000000
    }

  # controller definitions
  - controller_name: $(arg prefix)arm_controller
  - controller_name: $(arg prefix)gripper_controller

$(arg prefix)arm_controller:
  # Connection type (USB or Ethernet)
  # - connection_type: USB
  - connection_type: Ethernet

  # Ethernet connection config
  - ethernet: {
      master_controller_ip: $(arg ip)
      master_controller_port: $(arg port)
    }

  # Serial Port connection config
  - serial_port: {
      master_controller_device_name: /dev/ttyUSB0,
      master_controller_baudrate: 3000000
    }

  # controller definitions
  - controller_name: $(arg prefix)arm_controller
