publish_rate: 100
outer_force: 15
inner_force: 11
# 1123
outer_open_position:  10000
outer_close_position: 36000
speed_limit: 3
grasping_inner_force : 8
inner_open_motor_position: 3320
inner_close_motor_position: 3900
