publish_rate: 100
outer_force: 15
inner_force: 14
# 1123
outer_open_position:  -21000
outer_close_position: 36000
speed_limit: 3
grasping_inner_force : 10
inner_open_motor_position: 2500
inner_close_motor_position: 2222
inner_slight_open: 45
