controller_list:
  - name: fake_a_iiwa_controller
    joints:
      - a_iiwa_joint_1
      - a_iiwa_joint_2
      - a_iiwa_joint_3
      - a_iiwa_joint_4
      - a_iiwa_joint_5
      - a_iiwa_joint_6
      - a_iiwa_joint_7
  - name: fake_b_iiwa_controller
    joints:
      - b_iiwa_joint_1
      - b_iiwa_joint_2
      - b_iiwa_joint_3
      - b_iiwa_joint_4
      - b_iiwa_joint_5
      - b_iiwa_joint_6
      - b_iiwa_joint_7
  - name: fake_iiwa_two_robots_controller
    joints:
      - a_iiwa_joint_1
      - a_iiwa_joint_2
      - a_iiwa_joint_3
      - a_iiwa_joint_4
      - a_iiwa_joint_5
      - a_iiwa_joint_6
      - a_iiwa_joint_7
      - b_iiwa_joint_1
      - b_iiwa_joint_2
      - b_iiwa_joint_3
      - b_iiwa_joint_4
      - b_iiwa_joint_5
      - b_iiwa_joint_6
      - b_iiwa_joint_7
  - name: fake_a_iiwa_arm_controller
    joints:
      - a_iiwa_joint_1
      - a_iiwa_joint_2
      - a_iiwa_joint_3
      - a_iiwa_joint_4
      - a_iiwa_joint_5
      - a_iiwa_joint_6
      - a_iiwa_joint_7
  - name: fake_a_iiwa_hand_controller
    joints:
      - a_iiwa_robotiq_85_left_knuckle_joint
  - name: fake_a_iiwa_groups_controller
    joints:
      - a_iiwa_joint_1
      - a_iiwa_joint_2
      - a_iiwa_joint_3
      - a_iiwa_joint_4
      - a_iiwa_joint_5
      - a_iiwa_joint_6
      - a_iiwa_joint_7
      - a_iiwa_robotiq_85_left_knuckle_joint
  - name: fake_b_iiwa_arm_controller
    joints:
      - b_iiwa_joint_1
      - b_iiwa_joint_2
      - b_iiwa_joint_3
      - b_iiwa_joint_4
      - b_iiwa_joint_5
      - b_iiwa_joint_6
      - b_iiwa_joint_7
  - name: fake_b_iiwa_hand_controller
    joints:
      - b_iiwa_robotiq_85_left_knuckle_joint
  - name: fake_b_iiwa_groups_controller
    joints:
      - b_iiwa_joint_1
      - b_iiwa_joint_2
      - b_iiwa_joint_3
      - b_iiwa_joint_4
      - b_iiwa_joint_5
      - b_iiwa_joint_6
      - b_iiwa_joint_7
      - b_iiwa_robotiq_85_left_knuckle_joint
  - name: fake_iiwa_two_robots_groups_controller
    joints:
      - a_iiwa_joint_1
      - a_iiwa_joint_2
      - a_iiwa_joint_3
      - a_iiwa_joint_4
      - a_iiwa_joint_5
      - a_iiwa_joint_6
      - a_iiwa_joint_7
      - a_iiwa_robotiq_85_left_knuckle_joint
      - b_iiwa_joint_1
      - b_iiwa_joint_2
      - b_iiwa_joint_3
      - b_iiwa_joint_4
      - b_iiwa_joint_5
      - b_iiwa_joint_6
      - b_iiwa_joint_7
      - b_iiwa_robotiq_85_left_knuckle_joint