controller_list:
  - name: a_iiwa/PositionJointInterface_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints: 
      - a_iiwa_joint_1
      - a_iiwa_joint_2
      - a_iiwa_joint_3
      - a_iiwa_joint_4
      - a_iiwa_joint_5
      - a_iiwa_joint_6
      - a_iiwa_joint_7
  - name: b_iiwa/PositionJointInterface_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints: 
      - b_iiwa_joint_1
      - b_iiwa_joint_2
      - b_iiwa_joint_3
      - b_iiwa_joint_4
      - b_iiwa_joint_5
      - b_iiwa_joint_6
      - b_iiwa_joint_7
