# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: a_iiwa_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - a_iiwa_joint_1
    - a_iiwa_joint_2
    - a_iiwa_joint_3
    - a_iiwa_joint_4
    - a_iiwa_joint_5
    - a_iiwa_joint_6
    - a_iiwa_joint_7
    - a_iiwa_r85grobotiq_85_left_knuckle_joint
    - b_iiwa_joint_1
    - b_iiwa_joint_2
    - b_iiwa_joint_3
    - b_iiwa_joint_4
    - b_iiwa_joint_5
    - b_iiwa_joint_6
    - b_iiwa_joint_7
    - b_iiwa_r85grobotiq_85_left_knuckle_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: a_iiwa_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - a_iiwa_joint_1
      - a_iiwa_joint_2
      - a_iiwa_joint_3
      - a_iiwa_joint_4
      - a_iiwa_joint_5
      - a_iiwa_joint_6
      - a_iiwa_joint_7
  - name: a_iiwa_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      []
  - name: a_iiwa_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - a_iiwa_joint_1
      - a_iiwa_joint_2
      - a_iiwa_joint_3
      - a_iiwa_joint_4
      - a_iiwa_joint_5
      - a_iiwa_joint_6
      - a_iiwa_joint_7
      - a_iiwa_r85grobotiq_85_left_knuckle_joint
  - name: b_iiwa_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - b_iiwa_joint_1
      - b_iiwa_joint_2
      - b_iiwa_joint_3
      - b_iiwa_joint_4
      - b_iiwa_joint_5
      - b_iiwa_joint_6
      - b_iiwa_joint_7
  - name: b_iiwa_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      []
  - name: b_iiwa_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - b_iiwa_joint_1
      - b_iiwa_joint_2
      - b_iiwa_joint_3
      - b_iiwa_joint_4
      - b_iiwa_joint_5
      - b_iiwa_joint_6
      - b_iiwa_joint_7
      - b_iiwa_r85grobotiq_85_left_knuckle_joint
  - name: iiwa_two_robots_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - a_iiwa_joint_1
      - a_iiwa_joint_2
      - a_iiwa_joint_3
      - a_iiwa_joint_4
      - a_iiwa_joint_5
      - a_iiwa_joint_6
      - a_iiwa_joint_7
      - a_iiwa_r85grobotiq_85_left_knuckle_joint
      - b_iiwa_joint_1
      - b_iiwa_joint_2
      - b_iiwa_joint_3
      - b_iiwa_joint_4
      - b_iiwa_joint_5
      - b_iiwa_joint_6
      - b_iiwa_joint_7
      - b_iiwa_r85grobotiq_85_left_knuckle_joint