tray_id:
  part_4 : "set3_tray_1_partition_4",
  part_5 : "set3_tray_2_partition_6",
  part_6 : "set3_tray_1_partition_3",
  part_7 : "set3_tray_1_partition_2",
  part_8 : "set3_tray_2_partition_1",
  part_9 : "set3_tray_2_partition_4",
  part_10: "set3_tray_2_partition_7",
  part_11: "set3_tray_1_partition_1",
  part_12: "set3_tray_2_partition_3",
  part_13: "set3_tray_1_partition_5",
  part_14: "set3_tray_2_partition_2",
  part_15: "set3_tray_2_partition_5",
  part_16: "set3_tray_2_partition_8",
