methods:
  08_KZAF1075NA4WA55GA20AA0: 2
  09_EDCS10: 1
  10_CLBPS10_17_4: 1
  12_CLBUS6-9-9.5: 1
  14_BGPSL6-9-L30-F8: 2
  15_SLBNR6: 1

settings:
  04_37D-GEARMOTOR-50-70:
    Matching_Algorithm: Combined
  05_MBRFA30-2-P6:
    Matching_Algorithm: Combined
  07_SBARB6200ZZ_30:
    Matching_Algorithm: Combined
  10_CLBPS10_17_4:
    Scene_Minimal_Cluster_Size: 50
  12_CLBPS10_17_4:
    Scene_Minimal_Cluster_Size: 50
