$(arg prefix)gripper_controller:
  gripper_action:
    type: robot_controllers/ParallelGripperController
    l_gripper_joint: $(arg prefix)l_gripper_finger_joint
    r_gripper_joint: $(arg prefix)r_gripper_finger_joint
    centering:
      p: 1000.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0

gazebo:
  $(arg prefix)l_gripper_finger_joint:
    position:
      p: 5000.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
  $(arg prefix)r_gripper_finger_joint:
    position:
      p: 5000.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
