$(arg prefix)controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - $(arg prefix)shoulder_pan_joint
    - $(arg prefix)shoulder_lift_joint
    - $(arg prefix)elbow_joint
    - $(arg prefix)wrist_1_joint
    - $(arg prefix)wrist_2_joint
    - $(arg prefix)wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    $(arg prefix)shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    $(arg prefix)shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    $(arg prefix)elbow_joint: {trajectory: 0.1, goal: 0.1}
    $(arg prefix)wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    $(arg prefix)wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    $(arg prefix)wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
