robot_ip: $(arg ip)
reverse_port: $(arg reverse_port)
script_sender_port: $(arg script_sender_port)
script_file: $(find ur_robot_driver)/resources/ros_control.urscript
output_recipe_file: $(find ur_robot_driver)/resources/rtde_output_recipe.txt
input_recipe_file: $(find ur_robot_driver)/resources/rtde_input_recipe.txt
headless_mode: false
tf_prefix: ""
use_tool_communication: $(arg use_tool_communication)
tool_voltage: 0
tool_parity: 0
tool_baud_rate: 115200
tool_stop_bits: 1
tool_rx_idle_chars: 1.5
tool_tx_idle_chars: 3.5
