camera_type: PhoXiCamera
camera_name: camera
robot_name: arm
eye_on_hand: true
robot_base_frame: basement_link
robot_effector_frame: arm_ee_link
robot_effector_tip_frame: magnet_link
camera_frame: calibrated_camera
marker_id: 26
marker_size: 0.07
planarity_tolerance: 0.001
initpose: [0.10,  0.10, 0.35, 0, 90, 0]
keyposes:
  - [0.20,  0.10, 0.16, 30, 25, 0]
  - [0.20,  0.00, 0.16, 30, 25, 0]
  - [0.20, -0.10, 0.16, 30, 25, 0]

# - [0.15, -0.15, 0.25, 30, 25, 0]
# - [0.15,  0.00, 0.25, 30, 25, 0]
# - [0.15,  0.15, 0.25, 30, 25, 0]

# - [0.40,  0.15, 0.15, 30, 25, 0]
# - [0.40,  0.00, 0.15, 30, 25, 0]
# - [0.40, -0.15, 0.15,  0, 25, 0]

  - [0.00, -0.15, 0.16, 30, 25, 0]
  - [0.00,  0.00, 0.16, 30, 25, 0]
  - [0.00,  0.15, 0.16, 30, 25, 0]

camera_body_frame: camera
camera_optical_frame: sensor
