camera_type: PhoXiCamera
camera_name: camera
robot_name: arm
eye_on_hand: true
robot_base_frame: basement_link
robot_effector_frame: arm_ee_link
robot_effector_tip_frame: magnet_link
camera_frame: calibrated_camera
marker_id: 26
marker_size: 0.186
planarity_tolerance: 0.001
initpose: [0.30,  0.00, 0.75, 90, 0, 0]
keyposes:
  - [ 0.05,  0.00, 0.75,  90, -30,   0]
  - [ 0.20,  0.00, 0.75,  90, -15,   0]
  - [ 0.30,  0.00, 0.75,  90,   0,   0]
  - [ 0.45,  0.00, 0.75,  90,  15,   0]
  - [ 0.60,  0.00, 0.75,  90,  30,   0]
  - [ 0.30, -0.35, 0.75, 120,   0,   0]
  - [ 0.30, -0.15, 0.75, 105,   0,   0]
  - [ 0.30,  0.15, 0.75,  75,   0,   0]
  - [ 0.30,  0.35, 0.75,  60,   0,   0]

camera_body_frame: camera
camera_optical_frame: sensor
