<?xml version="1.0"?>

<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

This is the URDF model for the Intel RealSense 430 camera, in it's
aluminum peripherial evaluation case.
-->

<robot name="sensor_sr305" xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:macro name="sensor_sr305" params="prefix parent *origin">
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <!-- The following values are approximate, and the camera node
    publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="sr305_cam_depth_to_color_offset" value="0.02403"/>
    <xacro:property name="sr305_cam_depth_to_projector_offset" value="0.04785"/>

    <!-- The following values model the aluminum peripherial case for the
      SR305 camera, with the camera joint represented by the actual
      peripheral camera tripod mount -->
    <xacro:property name="sr305_cam_width" value="0.140"/>
    <xacro:property name="sr305_cam_height" value="0.0255"/>
    <xacro:property name="sr305_cam_depth" value="0.0095"/>
    <xacro:property name="sr305_cam_mount_from_center_offset" value="0.0160"/>

    <!-- The following offset is relative to the physical SR305 camera peripherial
      camera tripod mount -->
    <xacro:property name="sr305_cam_depth_px"
		    value="${sr305_cam_mount_from_center_offset}"/>
    <xacro:property name="sr305_cam_depth_py" value="-0.00754"/>
    <xacro:property name="sr305_cam_depth_pz" value="${sr305_cam_height/2}"/>

    <!-- <material name="aluminum"> -->
    <!--   <color rgba="0.5 0.5 0.5 1"/> -->
    <!-- </material> -->

    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${prefix}camera_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}camera_link" />
    </joint>

    <link name="${prefix}camera_link">
      <visual>
      <origin xyz="${sr305_cam_mount_from_center_offset} 0.0 ${sr305_cam_height/2}" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
	  <mesh filename="package://aist_description/device/meshes/SR305.stl"
		scale="0.001 0.001 0.001"/>
        </geometry>
	<material name="aluminum">
	  <color rgba="0.5 0.5 0.5 1"/>
	</material>
        <!-- <material name="aluminum"/> -->
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${sr305_cam_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${sr305_cam_depth} ${sr305_cam_width} ${sr305_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>

    <!-- camera depth joints and links -->
    <joint name="${prefix}camera_depth_joint" type="fixed">
      <origin xyz="${sr305_cam_depth_px} ${sr305_cam_depth_py} ${sr305_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="${prefix}camera_link"/>
      <child link="${prefix}camera_depth_frame" />
    </joint>
    <link name="${prefix}camera_depth_frame"/>

    <joint name="${prefix}camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}camera_depth_frame" />
      <child link="${prefix}camera_depth_optical_frame" />
    </joint>
    <link name="${prefix}camera_depth_optical_frame"/>

    <!-- camera IR joints and links -->
    <joint name="${prefix}camera_infra1_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${prefix}camera_depth_frame" />
      <child link="${prefix}camera_infra1_frame" />
    </joint>
    <link name="${prefix}camera_infra1_frame"/>

    <joint name="${prefix}camera_infra1_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}camera_infra1_frame" />
      <child link="${prefix}camera_infra1_optical_frame" />
    </joint>
    <link name="${prefix}camera_infra1_optical_frame"/>

    <!-- camera color joints and links -->
    <joint name="${prefix}camera_color_joint" type="fixed">
      <origin xyz="0 ${sr305_cam_depth_to_color_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}camera_depth_frame" />
      <child link="${prefix}camera_color_frame" />
    </joint>
    <link name="${prefix}camera_color_frame"/>

    <joint name="${prefix}camera_color_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}camera_color_frame" />
      <child link="${prefix}camera_color_optical_frame" />
    </joint>
    <link name="${prefix}camera_color_optical_frame"/>

    <!-- camera projector joints and links -->
    <joint name="${prefix}camera_projector_joint" type="fixed">
      <origin xyz="0 ${sr305_cam_depth_to_projector_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}camera_depth_frame" />
      <child link="${prefix}camera_projector_frame" />
    </joint>
    <link name="${prefix}camera_projector_frame"/>

    <gazebo reference="${prefix}camera_depth_frame">
      <sensor type="depth" name="${prefix}camera">
	<always_on>true</always_on>
	<visualize>true</visualize>
	<camera>
          <horizontal_fov>1.034</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>R8G8B8</format>
          </image>
          <depth_camera>
          </depth_camera>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
	</camera>
	<plugin name="${prefix}cam_controller"
		filename="libgazebo_ros_openni_kinect.so">
          <baseline>0.2</baseline>
          <alwaysOn>true</alwaysOn>
          <updateRate>10.0</updateRate>
          <cameraName>${prefix}camera</cameraName>
          <frameName>${prefix}camera_color_optical_frame</frameName>
          <imageTopicName>color/image_raw</imageTopicName>
          <cameraInfoTopicName>color/camera_info</cameraInfoTopicName>
          <depthImageTopicName>aligned_depth_to_color/image_raw</depthImageTopicName>
          <depthImageCameraInfoTopicName>aligned_depth_to_color/camera_info</depthImageCameraInfoTopicName>
          <pointCloudTopicName>depth/points</pointCloudTopicName>
          <pointCloudCutoff>0.1</pointCloudCutoff>
          <!-- <hackBaseline>0.07</hackBaseline> -->
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
          <CxPrime>0.0</CxPrime>
          <Cx>0.0</Cx>
          <Cy>0.0</Cy>
          <focalLength>0.0</focalLength>
	</plugin>
      </sensor>
    </gazebo>

  </xacro:macro>
</robot>
