# Goal
string robot_name
geometry_msgs/PoseStamped pose
bool pick
string gripper_command
float32 grasp_offset
float32 approach_offset
bool liftup_after
float32 speed_fast
float32 speed_slow
float32 acc_fast
float32 acc_slow
---
# Result
bool success
---
# Feedback
geometry_msgs/PoseStamped current_pose
