# Goal
string robot_name
geometry_msgs/PoseStamped pose
bool pick
string gripper_command
float32 grasp_offset
float32 approach_offset
bool liftup_after
float32 speed_fast
float32 speed_slow
float32 acc_fast
float32 acc_slow
---
# Result
uint8 SUCCESS=0
uint8 MOVE_FAILURE=1
uint8 PICK_FAILURE=2

int32 result
---
# Feedback
geometry_msgs/PoseStamped current_pose
