controller_list:
  - name: a_khi_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - a_khi_joint1
      - a_khi_joint2
      - a_khi_joint3
      - a_khi_joint4
      - a_khi_joint5
      - a_khi_joint6
  - name: a_khi_gripper_controller
    type: GripperCommand
    action_ns: gripper_action
    default: true
    parallel: true
    joint:
      - a_khi_l_gripper_finger_joint
      - a_khi_r_gripper_finger_joint
  - name: b_khi_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - b_khi_joint1
      - b_khi_joint2
      - b_khi_joint3
      - b_khi_joint4
      - b_khi_joint5
      - b_khi_joint6
