<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
        name="dtorobo_base_scene" >

  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="a_torobo_x" value="0"/>
  <xacro:property name="a_torobo_y" value="-0.4875"/>
  <xacro:property name="b_torobo_x" value="0"/>
  <xacro:property name="b_torobo_y" value="0.4875"/>
  <xacro:property name="bots_z"	    value="0.785"/>

  <!-- common stuff -->
  <xacro:include filename="$(find aist_gazebo)/urdf/aist_base_scene.gazebo"/>

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <link name="world"/>

  <xacro:include filename="$(find aist_description)/object/urdf/aist_box.xacro"/>
  <xacro:property name="table_w" value="0.9"/>
  <xacro:property name="table_l" value="0.75"/>
  <xacro:property name="table_h" value="0.01"/>
  <xacro:aist_box boxname="workbox"
		  box_w="${table_w}" box_l="${table_l}" box_h="${table_h}"
		  parent="world">
    <origin xyz="${-table_w/2} ${-table_l/2} ${bots_z -table_h}" rpy="0 0 0"/>
  </xacro:aist_box>
  <link name="workspace_center"/>
  <joint name="world_to_workspace" type="fixed">
    <parent link="world"/>
    <child  link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- robot arms -->
  <xacro:include filename="$(find aist_description)/device/urdf/torobo_arm.urdf.xacro"/>
  <xacro:torobo_arm prefix="a_torobo_"/>
  <joint name="world_a_torobo_joint" type="fixed">
    <parent link="world"/>
    <child  link="a_torobo_base"/>
    <origin xyz="${a_torobo_x} ${a_torobo_y} ${bots_z}" rpy="0 0 ${pi/2}"/>
  </joint>

  <xacro:torobo_arm prefix="b_torobo_"/>
  <joint name="world_b_torobo_joint" type="fixed">
    <parent link="world"/>
    <child  link="b_torobo_base"/>
    <origin xyz="${b_torobo_x} ${b_torobo_y} ${bots_z}" rpy="0 0 ${-pi/2}"/>
  </joint>

  <!-- Attach grippers -->
  <xacro:include filename="$(find aist_description)/device/urdf/torobo_gripper.urdf.xacro"/>
  <xacro:torobo_gripper prefix="a_torobo_"/>
  <joint name="a_torobo_arm_gripper_joint" type="fixed">
    <parent link="a_torobo_arm/ee_link"/>
    <child  link="a_torobo_gripper/base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <xacro:torobo_gripper prefix="b_torobo_"/>
  <joint name="b_torobo_arm_gripper_joint" type="fixed">
    <parent link="b_torobo_arm/ee_link"/>
    <child  link="b_torobo_gripper/base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Add PhoXi 3D scanner -->
  <xacro:include filename="$(find o2as_phoxi_camera)/urdf/phoxi_m_camera.urdf.xacro"/>
  <xacro:phoxi_m_camera prefix="b_" parent="world">
    <origin xyz="0.547941636523
		 -0.00827443204237
		 1.67030171767"
	    rpy="${-151.493605482*pi/180}
		 ${0.698490882792*pi/180}
		 ${85.0482907121*pi/180}"/>
  </xacro:phoxi_m_camera>

</robot>
