<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
        name="pgrp_base_scene" >

  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="a_bot_x" value="0"/>
  <xacro:property name="a_bot_y" value="-0.4875"/>
  <!-- <xacro:property name="a_bot_theta" value="${pi}"/> -->
  <xacro:property name="b_bot_x" value="0"/>
  <xacro:property name="b_bot_y" value="0.4875"/>
  <xacro:property name="b_bot_theta" value="${pi}"/>

  <xacro:property name="bots_z" value="0.77"/>

  <!-- This is the main file defining our robot arrangement and physical environment. -->

  <!-- common stuff -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro"/>
  <xacro:include filename="$(find aist_gazebo)/urdf/aist_base_scene.gazebo"/>

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <link name="world"/>

  <xacro:include filename="$(find aist_description)/object/urdf/aist_box.xacro"/>
  <xacro:property name="table_w" value="0.9"/>
  <xacro:property name="table_l" value="1.8"/>
  <xacro:property name="table_h" value="0.01"/>
  <xacro:aist_box boxname="workbox"
		  box_w="${table_w}" box_l="${table_l}" box_h="${table_h}"
		  parent="world">
    <origin xyz="${-table_w/2} ${-table_l/2} ${bots_z - table_h}" rpy="0 0 0"/>
  </xacro:aist_box>
  <link name="workspace_center"/>
  <joint name="world_to_workspace" type="fixed">
    <parent link="world"/>
    <child link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- robot arms -->
  <xacro:include filename="$(find aist_description)/device/urdf/ur5.urdf.xacro"/>
  <xacro:ur5_robot prefix="a_bot_" joint_limited="false"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>

  <xacro:ur5_robot prefix="b_bot_" joint_limited="false"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>

  <joint name="world_a_bot_joint" type="fixed">
    <parent link="world"/>
    <child  link= "a_bot_base_link"/>
    <origin xyz="${a_bot_x} ${a_bot_y} ${bots_z}" rpy="0 0 0"/>
  </joint>

  <joint name="world_b_bot_joint" type="fixed">
    <parent link="world"/>
    <child  link= "b_bot_base_link"/>
    <origin xyz="${b_bot_x} ${b_bot_y} ${bots_z}" rpy="0 0 ${b_bot_theta}"/>
  </joint>

  <!-- Spawn and attach force sensor -->
  <xacro:include filename="$(find aist_ftsensor)/urdf/ft300.urdf.xacro"/>
  <xacro:ft300 prefix="a_bot_" parent="a_bot_ee_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:ft300>
  <xacro:ft300 prefix="b_bot_" parent="b_bot_ee_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:ft300>

  <!-- Spawn and attach gripper -->
  <xacro:include filename="$(find o2as_precision_gripper)/urdf/precision_gripper.urdf.xacro" />
  <xacro:precision_gripper prefix="a_bot_"
			   grippername = "gripper"
			   parent = "a_bot_ft300_flange_link">
    <origin xyz="-0.004 0 0" rpy="${-pi/2} ${-0.2*pi/180} ${1.3*pi/180}"/>
    <!-- <origin xyz="-0.004 0 0" rpy="${-pi/2} 0 0"/> -->
  </xacro:precision_gripper>

  <xacro:include filename="$(find aist_description)/device/urdf/single_suction_gripper.urdf.xacro"/>
  <xacro:single_suction_gripper prefix="b_bot_"
  				parent="b_bot_ft300_flange_link">
    <origin xyz="0 0 0" rpy="0 ${0.2*pi/180} ${-0.4*pi/180}"/>
    <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
  </xacro:single_suction_gripper>

  <!-- Add virtual wall to avoid collisions-->
  <xacro:aist_box boxname="vwall1" box_w="0.01" box_l="0.3" box_h="0.5"
		  parent="world">
    <origin xyz="0.45 -0.15 ${bots_z}" rpy="0 0 0"/>
  </xacro:aist_box>

  <!-- Add PhoXi 3D scanner -->
  <xacro:include filename="$(find o2as_phoxi_camera/urdf/phoxi_m_camera.urdf.xacro"/>
  <xacro:phoxi_m_camera prefix="a_" parent="world">
    <origin xyz="0.484295583013
		 -0.0166431117381
		 1.40352762972"
	    rpy="${-152.276420805*pi/180}
		 ${-2.02008972972*pi/180}
		 ${86.5892287041*pi/180}"/>
  </xacro:phoxi_m_camera>

  <!-- Add RealSense camera -->
  <xacro:include filename="$(find aist_description)/device/urdf/_d435.urdf.xacro" />
  <xacro:sensor_d435 prefix="a_bot_" parent="a_bot_wrist_2_link">
    <origin xyz="0.0 -0.06 0.20" rpy="${0*pi/180} 0.0 ${pi/2}" />
  </xacro:sensor_d435>

</robot>
