<?xml version="1.0" ?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="cabinet">
  <xacro:include filename="$(find aist_description)/objects/urdf/aist_box.urdf.xacro"/>

  <xacro:macro name="cabinet"
	       params="prefix width length base_height
		       shelf1_height shelf2_height shelf3_height shelf4_height
		       back_height parent *origin">

    <xacro:property name="thickness"	value="0.030" />

    <xacro:aist_box name="${prefix}cabinet_base"
		    width="${width}"
		    length="${length - thickness}"
		    height="${base_height}"
		    parent="${parent}">
      <xacro:insert_block name="origin"/>
    </xacro:aist_box>

    <xacro:aist_box name="${prefix}cabinet_back"
		    width="${width}"
		    length="${thickness}"
		    height="${back_height}"
		    parent="${prefix}cabinet_base">
      <origin xyz="0 ${length - thickness} 0" rpy="0 0 0"/>
    </xacro:aist_box>

    <xacro:aist_box name="${prefix}cabinet_shelf1"
		    width="${width}"
		    length="${length - thickness}"
		    height="${thickness}"
		    parent="${prefix}cabinet_base">
      <origin xyz="0 0 ${shelf1_height - thickness}" rpy="0 0 0"/>
    </xacro:aist_box>

    <xacro:aist_box name="${prefix}cabinet_shelf2"
		    width="${width}"
		    length="${length - thickness}"
		    height="${thickness}"
		    parent="${prefix}cabinet_base">
      <origin xyz="0 0 ${shelf2_height - thickness}" rpy="0 0 0"/>
    </xacro:aist_box>

    <xacro:aist_box name="${prefix}cabinet_shelf3"
		    width="${width}"
		    length="${length - thickness}"
		    height="${thickness}"
		    parent="${prefix}cabinet_base">
      <origin xyz="0 0 ${shelf3_height - thickness}" rpy="0 0 0"/>
    </xacro:aist_box>

    <xacro:aist_box name="${prefix}cabinet_shelf4"
		    width="${width}"
		    length="${length - thickness}"
		    height="${thickness}"
		    parent="${prefix}cabinet_base">
      <origin xyz="0 0 ${shelf4_height - thickness}" rpy="0 0 0"/>
    </xacro:aist_box>

    <xacro:macro name="auxiliary_frame" params="parent framename *origin">
      <joint name="${parent}_${framename}" type="fixed">
	<parent link="${parent}" />
	<child link = "${parent}_${framename}"/>
	<xacro:insert_block name="origin"/>
      </joint>
      <link name="${parent}_${framename}"/>
    </xacro:macro>

    <xacro:auxiliary_frame parent="${prefix}cabinet_base" framename="origin">
      <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    </xacro:auxiliary_frame>

    <xacro:auxiliary_frame parent="${prefix}cabinet_base_origin"
			   framename="center">
      <origin xyz="${width/2} ${(length - thickness)/2} 0" rpy="0 0 0"/>
    </xacro:auxiliary_frame>

    <xacro:auxiliary_frame parent="${prefix}cabinet_shelf1" framename="origin">
      <origin xyz="0 0 ${thickness}" rpy="0 0 0"/>
    </xacro:auxiliary_frame>

    <xacro:auxiliary_frame parent="${prefix}cabinet_shelf1_origin"
			   framename="center">
      <origin xyz="${width/2} ${(length - thickness)/2} 0" rpy="0 0 0"/>
    </xacro:auxiliary_frame>

    <xacro:auxiliary_frame parent="${prefix}cabinet_shelf2" framename="origin">
      <origin xyz="0 0 ${thickness}" rpy="0 0 0"/>
    </xacro:auxiliary_frame>

    <xacro:auxiliary_frame parent="${prefix}cabinet_shelf2_origin"
			   framename="center">
      <origin xyz="${width/2} ${(length - thickness)/2} 0" rpy="0 0 0"/>
    </xacro:auxiliary_frame>

  </xacro:macro>
</robot>
