controller_list:
  - name: fake_a_khi_controller
    joints:
      - a_khi_joint1
      - a_khi_joint2
      - a_khi_joint3
      - a_khi_joint4
      - a_khi_joint5
      - a_khi_joint6
initial:  # Define initial robot poses.
  - group: a_khi
    pose: standing