<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="lehz40k2_30"  params="prefix parent *origin">

    <xacro:property name="length"	   value="0.1959"/>
    <xacro:property name="x_offset"	   value="0.1084"/>
    <xacro:property name="x_finger_offset" value="-0.0465"/>
    <xacro:property name="z_offset"	   value="0.0238"/>

    <!-- Body -->
    <joint name="${prefix}gripper_base_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}gripper_base_link"/>
      <xacro:insert_block name="origin"/>
    </joint>
    <link name="${prefix}gripper_base_link">
      <visual>
        <origin xyz="${x_offset} 0 ${z_offset}" rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <mesh filename="package://aist_description/devices/meshes/LEHZ40K2-30_BODY.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Gazebo/Blue">
          <color rgba="0.1 0.1 0.8 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="${x_offset} 0 ${z_offset}" rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <mesh filename="package://aist_description/devices/meshes/collision/LEHZ40K2-30_BODY.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
      <inertial>
	<mass value="1.56"/>
	<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
    </link>
    <gazebo reference="${prefix}gripper_base_link">
      <material>Gazebo/Blue</material>
      <selfCollide>True</selfCollide>
      <mu1>0.2</mu1>
      <mu2>0.2</mu2>
    </gazebo>

    <!-- Tip -->
    <joint name="${prefix}gripper_joint" type="fixed">
      <parent link="${prefix}gripper_base_link"/>
      <child  link="${prefix}gripper_link"/>
      <origin xyz="${length} 0 0" rpy="0 0 0"/>
    </joint>
    <link name="${prefix}gripper_link"/>

    <!-- Left finger -->
    <joint name="${prefix}l_gripper_finger_joint" type="prismatic">
      <origin xyz="${x_offset - x_finger_offset} 0 0" rpy="0 0 0"/>
      <parent link="${prefix}gripper_base_link"/>
      <child  link="${prefix}l_finger_link"/>
      <axis xyz="0 -1 0"/>
      <limit lower="0.015" upper="0.030" effort="130" velocity="0.15"/>
    </joint>
    <link name="${prefix}l_finger_link">
      <visual>
        <origin xyz="${x_finger_offset} 0.015 ${z_offset}"
		rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <mesh filename="package://aist_description/devices/meshes/LEHZ40K2-30_LFINGER.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Gazebo/Grey">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${x_finger_offset} 0.015 ${z_offset}"
		rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <mesh filename="package://aist_description/devices/meshes/collision/LEHZ40K2-30_LFINGER.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
      <inertial>
	<mass value="0.10"/>
	<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
    </link>
    <gazebo reference="${prefix}l_finger_link">
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <mu1>30.0</mu1>
      <mu2>30.0</mu2>
      <maxVel>1.0</maxVel>
      <minDepth>0.001</minDepth>
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Right finger -->
    <joint name="${prefix}r_gripper_finger_joint" type="prismatic">
      <origin xyz="${x_offset - x_finger_offset} 0 0" rpy="0 0 0"/>
      <parent link="${prefix}gripper_base_link"/>
      <child  link="${prefix}r_finger_link"/>
      <axis xyz="0 1 0"/>
      <limit lower="0.015" upper="0.030" effort="130" velocity="0.15"/>
    </joint>
    <link name="${prefix}r_finger_link">
      <visual>
        <origin xyz="${x_finger_offset} -0.015 ${z_offset}"
		rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <mesh filename="package://aist_description/devices/meshes/LEHZ40K2-30_RFINGER.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Gazebo/Grey">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${x_finger_offset} -0.015 ${z_offset}"
		rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <mesh filename="package://aist_description/devices/meshes/collision/LEHZ40K2-30_RFINGER.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
      <inertial>
	<mass value="0.10"/>
	<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
    </link>
    <gazebo reference="${prefix}r_finger_link">
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <mu1>30.0</mu1>
      <mu2>30.0</mu2>
      <maxVel>1.0</maxVel>
      <minDepth>0.001</minDepth>
      <material>Gazebo/Grey</material>
    </gazebo>

  </xacro:macro>

</robot>
