<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="magripper" >

  <xacro:include filename="$(find aist_phoxi_camera)/urdf/phoxi_m_camera.urdf.xacro"/>
  <xacro:include filename="$(find aist_description)/devices/urdf/magswitch_e30.urdf.xacro"/>
  <xacro:include filename="$(find aist_description)/devices/urdf/lehz40k2_30.urdf.xacro" />

  <xacro:macro name="pillar" params="name length diameter parent *origin">

    <joint name="${name}_joint" type="fixed">
      <parent link="${parent}"/>
      <child  link="${name}"/>
      <xacro:insert_block name="origin"/>
    </joint>

    <link name="${name}">
      <visual>
        <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${diameter} ${diameter}"/>
        </geometry>
        <material name="DarkGrey">
          <color rgba="0.3 0.3 0.3 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${diameter} ${diameter}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="0.3"/>
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
    </link>

    <joint name="${name}_flange_joint" type="fixed">
      <parent link="${name}"/>
      <child  link="${name}_flange"/>
      <origin xyz="${length} 0 0" rpy="0 0 0"/>
    </joint>

    <link name="${name}_flange"/>

    <gazebo reference="${name}">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

  </xacro:macro>

  <xacro:macro name="magripper" params="prefix parent *origin">

    <xacro:property name="diameter"			value="0.04"/>
    <xacro:property name="trunk_length"			value="0.23"/>
    <xacro:property name="camera_branch_length"		value="0.09"/>
    <xacro:property name="magnet_branch_length"		value="0.06"/>
    <xacro:property name="gripper_branch_length"	value="0.06"/>

    <xacro:pillar name="${prefix}magripper_base_link" parent="${parent}"
		  length="${trunk_length}" diameter="${diameter}">
      <xacro:insert_block name="origin"/>
    </xacro:pillar>

    <!-- PhoXi camera -->
    <xacro:pillar name="${prefix}magripper_camera_branch"
		  parent="${prefix}magripper_base_link"
		  length="${camera_branch_length}" diameter="${diameter}">
      <origin xyz="${trunk_length - diameter/2} 0 0"
	      rpy="0 ${-pi/2} ${pi/2}"/>
    </xacro:pillar>
    <xacro:phoxi_m_camera prefix="${prefix}"
			  parent="${prefix}magripper_camera_branch_flange">
      <origin xyz="0 0 -0.03" rpy="${-pi/2} 0 ${-pi/2}"/>
    </xacro:phoxi_m_camera>

    <!-- Magswitch_E30 magnet hand -->
    <xacro:pillar name="${prefix}magripper_magnet_branch"
		  parent="${prefix}magripper_base_link"
		  length="${magnet_branch_length}" diameter="${diameter}">
      <origin xyz="${trunk_length - diameter/2} 0 0"
	      rpy="0 ${-pi/4} ${pi/2}"/>
    </xacro:pillar>
    <xacro:magswitch_e30 prefix="${prefix}"
			 parent="${prefix}magripper_magnet_branch_flange">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:magswitch_e30>

    <!-- LEHZ40K2-30 two-finger gripper -->
    <xacro:pillar name="${prefix}magripper_gripper_branch"
		  parent="${prefix}magripper_base_link"
		  length="${gripper_branch_length}" diameter="${diameter}">
      <origin xyz="${trunk_length - diameter/2} 0 0"
	      rpy="0 ${-pi*3/4} ${pi/2}"/>
    </xacro:pillar>
    <xacro:lehz40k2_30 prefix="${prefix}"
		       parent="${prefix}magripper_gripper_branch_flange">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:lehz40k2_30>

  </xacro:macro>


  <xacro:macro name="magripper2" params="prefix parent *origin">

    <xacro:property name="diameter"			value="0.04"/>
    <xacro:property name="trunk_length"			value="0.11"/>
    <xacro:property name="magnet_branch_length"		value="0.06"/>
    <xacro:property name="gripper_branch_length"	value="0.06"/>

    <xacro:pillar name="${prefix}magripper_base_link" parent="${parent}"
		  length="${trunk_length}" diameter="${diameter}">
      <xacro:insert_block name="origin"/>
    </xacro:pillar>

    <!-- PhoXi camera -->
    <xacro:phoxi_m_camera prefix="${prefix}"
			  parent="${prefix}magripper_base_link_flange">
      <origin xyz="0 0 -0.03" rpy="${-pi/2} 0 ${-pi/2}"/>
    </xacro:phoxi_m_camera>

    <!-- Magswitch_E30 magnet hand -->
    <xacro:pillar name="${prefix}magripper_magnet_branch"
		  parent="${prefix}magripper_base_link"
		  length="${magnet_branch_length}" diameter="${diameter}">
      <origin xyz="${trunk_length - diameter/2 - 0.07} 0 0"
	      rpy="0 ${pi/4} 0"/>
    </xacro:pillar>
    <xacro:magswitch_e30 prefix="${prefix}"
			 parent="${prefix}magripper_magnet_branch_flange">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:magswitch_e30>

    <!-- LEHZ40K2-30 two-finger gripper -->
    <xacro:pillar name="${prefix}magripper_gripper_branch"
		  parent="${prefix}magripper_base_link"
		  length="${gripper_branch_length}" diameter="${diameter}">
      <origin xyz="${trunk_length - diameter/2 - 0.07} 0 0"
	      rpy="0 ${-pi/4} 0 "/>
    </xacro:pillar>
    <xacro:lehz40k2_30 prefix="${prefix}"
		       parent="${prefix}magripper_gripper_branch_flange">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:lehz40k2_30>

  </xacro:macro>

  <xacro:macro name="magripper3" params="prefix parent *origin">

    <xacro:property name="gripper_x_offset" value="0.075"/>
    <xacro:property name="gripper_y_offset" value="-0.050"/>
    <xacro:property name="gripper_z_offset" value="0.050"/>
    <xacro:property name="magnet_y_offset" value="-0.174"/>
    <!-- <xacro:property name="camera_x_offset" value="0.298"/> -->
    <xacro:property name="camera_x_offset" value="0.180"/>
    <xacro:property name="camera_y_offset" value="-0.1145"/>
    <xacro:property name="camera_z_offset" value="-0.0355"/>

    <joint name="${prefix}magripper_base_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}magripper_base_link"/>
      <xacro:insert_block name="origin"/>
    </joint>

    <link name="${prefix}magripper_base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://aist_description/devices/meshes/magripper_base.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Gazebo/Grey">
          <color rgba="0.7 0.7 0.7 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="$0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://aist_description/devices/meshes/collision/magripper_base.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>

      <!-- Required for Gazebo -->
      <inertial>
	<mass value="1.5"/>
	<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
    </link>

    <!-- <gazebo reference="${prefix}magripper_base_link"> -->
    <!--   <material>Gazebo/Grey</material> -->
    <!--   <selfCollide>True</selfCollide> -->
    <!-- </gazebo> -->

    <!-- Magswitch_E30 magnet hand -->
    <joint name="${prefix}magripper_magnet_axis_joint" type="fixed">
      <parent link="${prefix}magripper_base_link"/>
      <child  link="${prefix}magripper_magnet_axis_link"/>
      <origin xyz="${gripper_x_offset} 0 0"
	      rpy="${-pi/4} 0 0"/>
    </joint>
    <link name="${prefix}magripper_magnet_axis_link"/>
    
    <joint name="${prefix}magripper_magnet_flange_joint" type="fixed">
      <parent link="${prefix}magripper_magnet_axis_link"/>
      <child  link="${prefix}magripper_magnet_flange"/>
      <origin xyz="0 ${magnet_y_offset} ${gripper_z_offset}"
	      rpy="0 0 ${-pi/2}"/>
    </joint>
    <link name="${prefix}magripper_magnet_flange"/>
    
    <xacro:magswitch_e30 prefix="${prefix}"
    			 parent="${prefix}magripper_magnet_flange">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:magswitch_e30>

    <!-- LEHZ40K2-30 two-finger gripper -->
    <joint name="${prefix}magripper_gripper_axis_joint" type="fixed">
      <parent link="${prefix}magripper_base_link"/>
      <child  link="${prefix}magripper_gripper_axis_link"/>
      <origin xyz="${gripper_x_offset} 0 0"
	      rpy="${pi/4} 0 0"/>
    </joint>
    <link name="${prefix}magripper_gripper_axis_link"/>
    
    <joint name="${prefix}magripper_gripper_flange_joint" type="fixed">
      <parent link="${prefix}magripper_gripper_axis_link"/>
      <child  link="${prefix}magripper_gripper_flange"/>
      <origin xyz="0 ${gripper_y_offset} ${-gripper_z_offset}"
	      rpy="0 0 ${-pi/2}"/>
    </joint>
    <link name="${prefix}magripper_gripper_flange"/>

    <xacro:lehz40k2_30 prefix="${prefix}"
    		       parent="${prefix}magripper_gripper_flange">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:lehz40k2_30>
    
    <!-- PhoXi camera -->
    <joint name="${prefix}magripper_camera_flange_joint" type="fixed">
      <parent link="${prefix}magripper_base_link"/>
      <child  link="${prefix}magripper_camera_flange"/>
      <origin xyz="${camera_x_offset} ${camera_y_offset} ${camera_z_offset}"
	      rpy="${-pi/2} 0 ${pi}"/>
    </joint>
    <link name="${prefix}magripper_camera_flange"/>
    
    <xacro:phoxi_m_camera prefix="${prefix}"
    			  parent="${prefix}magripper_camera_flange">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:phoxi_m_camera>

  </xacro:macro>

</robot>
