<?xml version="1.0"?>
<robot name="tranbo" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Tranbo constants -->
  <xacro:property name="tranbo_length"		value="1.050"/>
  <xacro:property name="tranbo_width"		value="0.595"/>
  <!-- <xacro:property name="tranbo_height"	value="0.8788"/> -->
  <xacro:property name="tranbo_height"		value="0.882"/>
  <xacro:property name="tranbo_offset"		value="-0.225"/>
  <xacro:property name="tranbo_tread"		value="0.441"/>
  <xacro:property name="tranbo_wheel_mass"	value="2.0"/>
  <xacro:property name="tranbo_wheel_radius"	value="0.075"/>
  <xacro:property name="tranbo_wheel_length"	value="0.05"/>
  <xacro:property name="tranbo_caster_base"	value="0.840"/>
  <xacro:property name="tranbo_caster_radius"	value="0.065"/>
  <xacro:property name="tranbo_caster_length"	value="0.05"/>
  <xacro:property name="tranbo_caster_tread"	value="0.385"/>

  <!-- ========= Catser ========= -->
  <xacro:macro name="tranbo_caster" params="prefix parent front left">
    <link name="${prefix}caster_link">
      <inertial>
    	<mass value="4.3542"/>
    	<inertia ixx="0.0045" ixy="0" ixz="0"
		 iyy="0.005" iyz="0" izz="0.0045"/>
      </inertial>
      <visual>
	<geometry>
	  <cylinder radius="${tranbo_caster_radius}"
		    length="${tranbo_caster_length}"/>
	</geometry>
	<material name="">
          <color rgba="0 0 0 1" />
	</material>
      </visual>
      <collision>
	<geometry>
	  <cylinder radius="${tranbo_caster_radius}"
		    length="${tranbo_caster_length}"/>
	</geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}caster_link">
      <mu1>0.0</mu1>
      <mu2>0.0</mu2>
      <material>Gazebo/Black</material>
    </gazebo>
    
    <joint name="${prefix}caster_joint" type="fixed">
      <origin xyz="${tranbo_caster_base/2 if front else -tranbo_caster_base/2}
		   ${tranbo_caster_tread/2 if left else -tranbo_caster_tread/2}
		   ${tranbo_caster_radius + 0.005}"
	      rpy="${pi/2} 0 0" />
      <parent link="${parent}" />
      <child  link="${prefix}caster_link" />
    </joint>
  </xacro:macro>
  
  <!-- ========= Wheel ========= -->
  <xacro:macro name="tranbo_wheel" params="prefix parent left">
    <link name="${prefix}wheel_link">
      <inertial>
    	<origin xyz="0 0 0" rpy="0 0 0"/>
    	<mass value="4.3542"/>
    	<inertia ixx="0.0045" ixy="0" ixz="0"
		 iyy="0.005"  iyz="0" izz="0.0045"/>
      </inertial>
      <visual>
    	<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    	<geometry>
	  <cylinder radius="${tranbo_wheel_radius}"
		    length="${tranbo_wheel_length}"/>
    	</geometry>
    	<material name="">
          <color rgba="0.086 0.506 0.767 1" />
    	</material>
      </visual>
      <collision>
    	<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    	<geometry>
	  <cylinder radius="${tranbo_wheel_radius}"
		    length="${tranbo_wheel_length}"/>
    	</geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}wheel_link">
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <mu1>10</mu1>
      <mu2>10</mu2>
      <fdir1>1 0 0</fdir1>
      <maxVel>1.0</maxVel>
      <minDepth>0.003</minDepth>
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="${prefix}wheel_joint" type="continuous">
      <origin xyz="0
		   ${tranbo_tread/2 if left else -tranbo_tread/2}
		   ${tranbo_wheel_radius}"
	      rpy="0 0 0"/>
      <parent link="${parent}" />
      <child  link="${prefix}wheel_link" />
      <axis xyz="0 1 0" />
      <limit effort="8.85" velocity="34.8" />
    </joint>
    <gazebo reference="${prefix}wheel_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>
  </xacro:macro>
  
  <!-- ========= Tranbo ========= -->
  <xacro:macro name="tranbo" params="prefix">
    <!-- Body -->
    <link name="${prefix}base_link">
      <inertial>
	<origin xyz="-0.0036 0.0 0.0014" rpy="0 0 0"/>
	<mass value="70.1294" />
	<inertia ixx="1.225"  ixy="0.0099"  ixz="0.0062"
		 iyy="1.2853" iyz="-0.0034" izz="0.987"/>
      </inertial>
      <visual>
        <origin xyz="${tranbo_offset} 0 ${tranbo_height}"
		rpy="0 0 ${-pi/2}" />
	<geometry>
          <mesh filename="package://aist_description/devices/meshes/TRanbo.stl"
		scale="0.001 0.001 0.001"/>
	</geometry>
	<material name="">
          <color rgba="1 1 1 1" />
	</material>
      </visual>
      <collision>
        <origin xyz="0 0 ${tranbo_height/2 + 0.04}" rpy="0 0 0" />
	<geometry>
	  <box size="${tranbo_length} ${tranbo_width} ${tranbo_height - 0.04}"/>
	</geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}base_link">
      <kp>100000000.0</kp>
      <kd>10.0</kd>
      <mu1>0.1</mu1>
      <mu2>0.1</mu2>
      <fdir1>1 0 0</fdir1>
      <maxVel>10.0</maxVel>
      <minDepth>0.0005</minDepth>
    </gazebo>

    <!-- Basement of the arm -->
    <joint name="${prefix}basement_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child  link="${prefix}basement_link"/>
      <origin xyz="${tranbo_offset} 0 ${tranbo_height}" rpy="0 0 0"/>
    </joint>
    <link name="${prefix}basement_link"/>

    <!-- Front-left caster -->
    <xacro:tranbo_caster prefix="${prefix}front_left_"
			 parent="${prefix}base_link"
			 front="True" left="True"/>
    
    <!-- Front-right caster -->
    <xacro:tranbo_caster prefix="${prefix}front_right_"
			 parent="${prefix}base_link"
			 front="True" left="False"/>
    
    <!-- Rear-left caster -->
    <xacro:tranbo_caster prefix="${prefix}rear_left_"
			 parent="${prefix}base_link"
			 front="False" left="True"/>
    
    <!-- Front-right caster -->
    <xacro:tranbo_caster prefix="${prefix}rear_right_"
			 parent="${prefix}base_link"
			 front="False" left="False"/>
    
    <!-- Left wheel -->
    <xacro:tranbo_wheel prefix="${prefix}l_"
			parent="${prefix}base_link"
			left="True"/>
    
    <!-- Right wheel -->
    <xacro:tranbo_wheel prefix="${prefix}r_"
			parent="${prefix}base_link"
			left="False"/>
  </xacro:macro>

</robot>
















