<?xml version="1.0"?>
<robot name="tranbo" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="tranbo" params="prefix">

    <!-- Tranbo constants -->
    <xacro:property name="tranbo_length"	value="1.050"/>
    <xacro:property name="tranbo_width"		value="0.595"/>
    <!-- <xacro:property name="tranbo_height"	value="0.8788"/> -->
    <xacro:property name="tranbo_height"	value="0.882"/>
    <xacro:property name="tranbo_offset"	value="-0.225"/>
    <xacro:property name="tranbo_tread"		value="0.441"/>
    <xacro:property name="tranbo_wheel_mass"	value="2.0"/>
    <xacro:property name="tranbo_wheel_radius"	value="0.075"/>
    <xacro:property name="tranbo_wheel_length"	value="0.05"/>

    <!-- Body -->
    <link name="${prefix}base_link">
      <inertial>
	<origin xyz="-0.0036 0.0 0.0014" rpy="0 0 0"/>
	<mass value="70.1294" />
	<inertia ixx="1.225" ixy="0.0099" ixz="0.0062" iyy="1.2853" iyz="-0.0034" izz="0.987"/>
      </inertial>
      <visual>
        <origin xyz="${tranbo_offset} 0 ${tranbo_height}"
		rpy="0 0 ${-pi/2}" />
	<geometry>
          <mesh filename="package://aist_description/devices/meshes/TRanbo.stl" scale="0.001 0.001 0.001"/>
	</geometry>
	<material name="">
          <color rgba="1 1 1 1" />
	</material>
      </visual>
      <collision>
        <origin xyz="0 0 ${tranbo_height/2 + 0.005}" rpy="0 0 0" />
	<geometry>
	  <box size="${tranbo_length} ${tranbo_width} ${tranbo_height}"/>
	</geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}base_link">
      <kp>100000000.0</kp>
      <kd>10.0</kd>
      <mu1>0.1</mu1>
      <mu2>0.1</mu2>
      <fdir1>1 0 0</fdir1>
      <maxVel>10.0</maxVel>
      <minDepth>0.0005</minDepth>
    </gazebo>

    <!-- Basement of the arm -->
    <joint name="${prefix}basement_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child  link="${prefix}basement_link"/>
      <origin xyz="${tranbo_offset} 0 ${tranbo_height}" rpy="0 0 0"/>
    </joint>
    <link name="${prefix}basement_link"/>

    <!-- Left wheel -->
    <link name="${prefix}l_wheel_link">
      <inertial>
    	<origin xyz="0 0 0" rpy="0 0 0"/>
    	<mass value="4.3542"/>
    	<inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.0045"/>
      </inertial>
      <visual>
    	<origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
    	<geometry>
	  <cylinder radius="${tranbo_wheel_radius}"
		    length="${tranbo_wheel_length}"/>
    	</geometry>
    	<material name="">
          <color rgba="0.086 0.506 0.767 1" />
    	</material>
      </visual>
      <collision>
    	<origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
    	<geometry>
	  <cylinder radius="${tranbo_wheel_radius}"
		    length="${tranbo_wheel_length}"/>
    	</geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}l_wheel_link">
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <mu1>10</mu1>
      <mu2>10</mu2>
      <fdir1>1 0 0</fdir1>
      <maxVel>1.0</maxVel>
      <minDepth>0.003</minDepth>
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="${prefix}l_wheel_joint" type="continuous">
      <origin xyz="0 ${tranbo_tread/2} ${tranbo_wheel_radius}" rpy="0 0 0"/>
      <parent link="${prefix}base_link" />
      <child  link="${prefix}l_wheel_link" />
      <axis xyz="0 1 0" />
      <limit effort="8.85" velocity="34.8" />
    </joint>
    <gazebo reference="${prefix}l_wheel_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>
      
    <!-- Right wheel -->
    <link name="${prefix}r_wheel_link">
      <inertial>
    	<origin xyz="0 0 0" rpy="0 0 0"/>
    	<mass value="4.3542"/>
    	<inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.0045"/>
      </inertial>
      <visual>
    	<origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
    	<geometry>
	  <cylinder radius="${tranbo_wheel_radius}"
		    length="${tranbo_wheel_length}"/>
    	</geometry>
    	<material name="">
          <color rgba="0.086 0.506 0.767 1" />
    	</material>
      </visual>
      <collision>
    	<origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
    	<geometry>
	  <cylinder radius="${tranbo_wheel_radius}"
		    length="${tranbo_wheel_length}"/>
    	</geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}r_wheel_link">
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <mu1>10</mu1>
      <mu2>10</mu2>
      <fdir1>1 0 0</fdir1>
      <maxVel>1.0</maxVel>
      <minDepth>0.003</minDepth>
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="${prefix}r_wheel_joint" type="continuous">
      <origin xyz="0 ${-tranbo_tread/2} ${tranbo_wheel_radius}" rpy="0 0 0"/>
      <parent link="${prefix}base_link" />
      <child  link="${prefix}r_wheel_link" />
      <axis xyz="0 1 0" />
      <limit effort="8.85" velocity="34.8" />
    </joint>
    <gazebo reference="${prefix}r_wheel_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>

  </xacro:macro>

</robot>
