<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="kitting_scene">
  <xacro:include filename="$(find o2as_scene_description)/urdf/kitting_bin.xacro" />
  <xacro:include filename="$(find o2as_scene_description)/urdf/kitting_tray.xacro" />
  <xacro:property name="rack_width" value=".640" />
  <xacro:property name="tray_width" value=".300" />
  <xacro:property name="tray_length" value=".210" />


 <!-- space for bin -->

 <!-- bin1_definition -->
 <xacro:property name="bin1_width" value="0.125"/>
 <xacro:property name="bin1_length" value="0.128"/>
 <xacro:property name="z_origin_offset_1" value="-.008" />

 <!-- bin2_definition -->
 <xacro:property name="bin2_width" value="0.112"/>
 <xacro:property name="bin2_length" value="0.201"/>
 <xacro:property name="z_origin_offset_2" value="-.009" />

 <!-- bin3_definition -->
 <xacro:property name="bin3_width" value="0.192"/>
 <xacro:property name="bin3_length" value="0.285"/>
 <xacro:property name="z_origin_offset_3" value="-.004" />

 <!-- A row of bin1 -->
 <xacro:property name="set1_x" value=".0"/>
 <xacro:property name="set1_y" value="0.36"/>
 <xacro:property name="set1_z" value=".01"/>
 <!-- A row of bin2 -->
 <xacro:property name="set2_x" value=".20"/>
 <xacro:property name="set2_y" value="0.36"/>
 <xacro:property name="set2_z" value=".00"/>
 <!--set1_bin1_1_-->
  <xacro:kitting_bin_1 binname="set1_bin1_1" parent="workspace_center" z_origin_offset="-.008">
      <origin xyz=".0 0.2975 0.018" rpy="0 0 0" />
  </xacro:kitting_bin_1>
  <!--set1_bin1_2_-->
  <xacro:kitting_bin_1 binname="set1_bin1_2" parent="workspace_center" z_origin_offset="-.008">
      <origin xyz=".0 0.1725 0.018" rpy="0 0 0" />
  </xacro:kitting_bin_1>
  <!--set1_bin1_3_-->
  <xacro:kitting_bin_1 binname="set1_bin1_3" parent="workspace_center" z_origin_offset="-.008">
      <origin xyz=".0 0.0475 0.018" rpy="0 0 0" />
  </xacro:kitting_bin_1>
  <!--set1_bin1_4_-->
  <xacro:kitting_bin_1 binname="set1_bin1_4" parent="workspace_center" z_origin_offset="-.008">
      <origin xyz=".0 -0.0775 0.018" rpy="0 0 0" />
  </xacro:kitting_bin_1>
  <!--set1_bin1_5_-->
  <xacro:kitting_bin_1 binname="set1_bin1_5" parent="workspace_center" z_origin_offset="-.008">
      <origin xyz=".0 -0.2025 0.018" rpy="0 0 0" />
  </xacro:kitting_bin_1>
  <!--set2_bin2_1_-->
  <xacro:kitting_bin_2 binname="set2_bin2_1" parent="workspace_center" z_origin_offset="-.009">
      <origin xyz=".20 0.304 0.009" rpy="0 0 0" />
  </xacro:kitting_bin_2>
  <!--set2_bin2_2_-->
  <xacro:kitting_bin_2 binname="set2_bin2_2" parent="workspace_center" z_origin_offset="-.009">
      <origin xyz=".20 0.192 0.009" rpy="0 0 0" />
  </xacro:kitting_bin_2>
  <!--set2_bin3_1_-->
  <xacro:kitting_bin_3 binname="set2_bin3_1" parent="workspace_center" z_origin_offset="-.004">
      <origin xyz=".20 0.04 0.004" rpy="0 0 0" />
  </xacro:kitting_bin_3>
  <!--set2_bin2_3_-->
  <xacro:kitting_bin_2 binname="set2_bin2_3" parent="workspace_center" z_origin_offset="-.009">
      <origin xyz=".20 -0.112 0.009" rpy="0 0 0" />
  </xacro:kitting_bin_2>
  <!--set2_bin2_4_-->
  <xacro:kitting_bin_2 binname="set2_bin2_4" parent="workspace_center" z_origin_offset="-.009">
      <origin xyz=".20 -0.224 0.009" rpy="0 0 0" />
  </xacro:kitting_bin_2>
 


  <!-- A row of tray -->
  <xacro:property name="set3_x" value="${-(bin1_length/2+tray_length/2)}" />
  <xacro:property name="set3_y" value="${.32-tray_width/2}" />
  <xacro:property name="set3_z" value=".007" />

  <!-- set3_tray_1 -->
  <xacro:kitting_tray trayname="set3_tray_1" parent="workspace_center">
    <origin xyz="${set3_x} ${set3_y} ${set3_z}" rpy="0 0 0" />
  </xacro:kitting_tray>
  <!-- set3_tray_2 -->
  <xacro:kitting_tray trayname="set3_tray_2" parent="workspace_center">
    <origin xyz="${set3_x} ${set3_y-tray_width} ${set3_z}" rpy="0 0 0" />
  </xacro:kitting_tray>
  
</robot>